export interface GameData {
  name: string;
  id: number;
  provider?: string;
}

export const PLAYNGO_GAME_NAMES_WITH_IDS: GameData[] = [
  { name: 'Book of Dead', id: 3004 },
  { name: 'Legacy of Dead', id: 3007 },
  { name: 'Reactoonz', id: 3022 },
  { name: 'Fire Joker', id: 3033 },
  { name: 'Gold King', id: 3036 },
  { name: 'Rise Of Athena', id: 3061 },
  { name: 'Xmas Joker', id: 3052 },
  { name: 'Legion Gold', id: 3085 },
  { name: 'Fu Er Dai', id: 3042 },
  { name: 'Myth', id: 3028 },
  { name: 'Amulet Of Dead', id: 3026 },
  { name: 'Jewel Box', id: 3000 },
  { name: 'Chinese New Year', id: 3024 },
  { name: 'Lost Chapter', id: 3045 },
  { name: 'Scroll Of Seth', id: 3079 },
  { name: 'Tome of Madness', id: 3091 },
  { name: 'Star Joker', id: 3015 },
  { name: 'Boat Bonanza', id: 3089 },
  { name: 'Fortune Teller', id: 3011 },
  { name: "King's Mask", id: 3046 },
  { name: 'Golden Legend', id: 3017 },
  { name: 'Pearl Lagoon', id: 3027 },
  { name: 'Inferno Star', id: 3030 },
  { name: 'Pyramids of Dead', id: 3048 },
  { name: 'Samba Carnival', id: 3002 },
  { name: 'Diamonds of the Realm', id: 3073 },
  { name: 'the Sword and the Grail', id: 3069 },
  { name: 'Ice Joker', id: 3070 },
  { name: 'Legacy Of Inca', id: 3057 },
  { name: 'Merlin And Morgana', id: 3041 },
  { name: 'Crystal Sun', id: 3059 },
  { name: 'Immor Tails', id: 3064 },
  { name: 'Rise Of Dead', id: 3035 },
  { name: 'Dawn Of Egypt', id: 3037 },
];

export const NOVOMATIC_GAME_NAMES_WITH_IDS: GameData[] = [
  { name: 'Book of Ra Classic', id: 12 },
  { name: 'Lucky Lady', id: 63 },
  { name: 'Money Game', id: 69 },
  { name: 'Bananas Go Bahamas', id: 5 },
  { name: 'Book of ra deluxe', id: 13 },
  { name: 'Always Hot', id: 107 },
  { name: "Lucky Lady's deluxe", id: 64 },
  { name: 'Money game deluxe', id: 70 },
  { name: 'Always Hot Deluxe', id: 105 },
  { name: 'Sizzling Hot Deluxe', id: 92 },
  { name: 'Sizzling Crowns', id: 117 },
  { name: "Dolphin's Pearl Deluxe", id: 26 },
  { name: 'Dolphins pearl classic', id: 25 },
  { name: 'Lord of the Ocean', id: 61 },
  { name: 'Pharaohs Gold II Deluxe', id: 76 },
  { name: 'Mario', id: 68 },
  { name: 'Always Hot Cubes', id: 104 },
  { name: 'Reel King', id: 81 },
  { name: 'Fruit farm', id: 34 },
  { name: 'Alchemist', id: 1 },
  { name: 'Just jewels', id: 54 },
  { name: 'Helena', id: 47 },
  { name: 'Sea sirens', id: 86 },
  { name: 'Sizzling hot deluxe', id: 92 },
  { name: 'Cryptic highway', id: 21 },
  { name: 'Just jewels deluxe', id: 55 },
  { name: 'Diamond 7', id: 24 },
  { name: 'Hot cubes', id: 48 },
  { name: 'Fruits and royals', id: 36 },
  { name: 'Inferno', id: 51 },
  { name: 'Sizzling gems', id: 90 },
  { name: 'Fruit sensation', id: 37 },
  { name: 'Mystery star', id: 72 },
  { name: 'Dazzling diamonds', id: 23 },
  { name: 'Mafia', id: 65 },
  { name: 'Glittering peaks', id: 40 },
  { name: 'Cosmic miracle', id: 20 },
  { name: 'Knightly valor', id: 58 },
  { name: 'Dolphins pearl deluxe', id: 26 },
  { name: 'Gryphons gold deluxe', id: 45 },
];

export const NETENT_GAME_NAMES_WITH_IDS: GameData[] = [
  { name: 'Dead or Alive', id: 1084 },
  { name: 'Koi Princess', id: 1096 },
  { name: 'Jack and the Beanstalk', id: 1058 },
  { name: 'Elements The Awakening', id: 1017 },
  { name: 'Jimi Hendrix', id: 1043 },
  { name: 'Victorious', id: 1010 },
  { name: 'Space Wars', id: 1016 },
  { name: 'Aloha', id: 1054 },
  { name: 'Spinata Grande', id: 1034 },
  { name: "Guns'N'Roses", id: 1042 },
  { name: 'Starburst', id: 1008 },
  { name: "Gonzo's Quest", id: 1007 },
  { name: 'Piggy Riches', id: 1001 },
  { name: 'Stickers', id: 1002 },
  { name: 'Flowers', id: 1005 },
  { name: 'Fruit Shop', id: 1003 },
  { name: 'Butterfly Staxx', id: 1060 },
  { name: 'Wild Water', id: 1019 },
  { name: 'Secrets Of Christmas', id: 1034 },
  { name: 'Vikings', id: 1063 },
  { name: 'Red Riding Hood', id: 1069 },
  { name: 'Hansel & Gretel', id: 1068 },
  { name: 'Mirror Mirror', id: 1067 },
  { name: 'Jungle Spirit', id: 1066 },
  { name: 'Coins Of Egypt', id: 1065 },
  { name: 'Blackjack', id: 1064 },
  { name: 'Jingle Spin', id: 1062 },
  { name: 'Wild Bazaar', id: 1061 },
  { name: 'Halloween Jack', id: 1059 },
  { name: 'Witch Craft Academy', id: 1057 },
  { name: 'Double Stacks', id: 1056 },
  { name: 'Dracula', id: 1055 },
  { name: 'HotLine', id: 1053 },
  { name: 'Hooks Heroes', id: 1052 },
  { name: 'Scruffy Duck', id: 1051 },
  { name: 'Golden Grimoire', id: 1070 },
  { name: 'Spell Cast', id: 1017 },
  { name: 'European Roulette Low Limit', id: 1071 },
  { name: 'Wild Turkey', id: 1082 },
  { name: 'Wings of Riches', id: 1091 },
  { name: 'Butterfly Staxx 2', id: 1090 },
  { name: 'Oceans Treasure', id: 1089 },
];

export const PRAGMATIC_GAME_NAMES_WITH_IDS: GameData[] = [
  { name: 'Gates of Olympus', id: 4031 },
  { name: 'Zeus & Hades', id: 4162 },
  { name: 'Sweet Bonanza', id: 4029 },
  { name: 'Wolf Gold', id: 4068 },
  { name: 'Triple Dragons', id: 4013 },
  { name: 'Big Bass Bonanza', id: 4047 },
  { name: 'The Dog House Megaways', id: 4089 },
  { name: 'Sugar Rush', id: 4060 },
  { name: 'Wild West Gold', id: 4052 },
  { name: 'Fire Strike 2', id: 4051 },
  { name: 'The Dog House', id: 4028 },
  { name: 'Big Bass Splash', id: 4057 },
  { name: 'Starlight Princess', id: 4032 },
  { name: 'Money Mouse', id: 4071 },
  { name: 'Fruit Party', id: 4066 },
  { name: 'Gems Bonanza', id: 4077 },
  { name: 'Juicy Fruits', id: 4045 },
  { name: 'Buffalo King', id: 4118 },
  { name: 'Book Of Tut', id: 4000 },
  { name: 'Book of Vikings', id: 4001 },
  { name: 'Return of the Dead', id: 4002 },
  { name: 'Scarab Queen', id: 4003 },
  { name: 'Heart of Rio', id: 4004 },
  { name: 'Madame Destiny', id: 4005 },
  { name: 'Ancient Egypt Classic', id: 4006 },
  { name: 'Wisdom of Athena', id: 4105 },
  { name: 'Jewel Rush', id: 4109 },
  { name: 'Supermania', id: 4116 },
  { name: 'Bali Dragon', id: 4139 },
  { name: 'Jeitinho Brasileiro', id: 4140 },
  { name: 'Hokkaido Wolf', id: 4141 },
  { name: 'Little Gem', id: 4145 },
  { name: '5 Lions Megaways', id: 4147 },
  { name: 'Rise of Samurai IV', id: 4163 },
  { name: 'The Conqueror', id: 4170 },
  { name: 'Hand of Midas 2', id: 4171 },
  { name: 'The Green Sun', id: 4176 },
  { name: 'Barbar', id: 4186 },
  { name: 'Golden Pig', id: 4142 },
  { name: 'Moonshot', id: 4135 },
];

export const PUSH_GAME_NAMES_WITH_IDS: GameData[] = [
  { name: 'Jammin Jars', id: 5008 },
  { name: 'Razor Shark', id: 5007 },
  { name: 'Fat Rabbit', id: 5001 },
  { name: 'TikiTumble', id: 5019 },
  { name: 'Retro Tapes', id: 5010 },
  { name: "Fish 'n' Nudge", id: 5016 },
  { name: 'Hearts Highway', id: 5000 },
  { name: 'Fat Santa', id: 5002 },
  { name: '10 Swords', id: 5003 },
  { name: 'Fire Hopper', id: 5005 },
  { name: 'Blaze Of Ra', id: 5006 },
  { name: 'Deadly 5', id: 5009 },
  { name: 'Fat Banker', id: 5011 },
  { name: 'Bison Battle', id: 5012 },
  { name: 'Crystal Catcher', id: 5013 },
  { name: 'Giga Jar', id: 5014 },
  { name: 'Joker Troupe', id: 5015 },
  { name: 'Mystery Mission To The Moon', id: 5017 },
  { name: 'Rat King', id: 5018 },
  { name: 'Generous Jack', id: 5020 },
  { name: 'Dinopolis', id: 5021 },
  { name: 'Jaguar Drop', id: 5022 },
  { name: 'Dj Cat', id: 5023 },
  { name: 'BigBite', id: 5024 },
  { name: 'Big Bam Book', id: 5025 },
  { name: 'Retro Sweets', id: 5026 },
];

export const POPULAR_GAME_NAMES_WITH_IDS: GameData[] = [
  { name: 'Gates of Olympus', id: 4031, provider: 'Pragmatic Play' },
  { name: 'Razor Shark', id: 5007, provider: 'Push Gaming' },
  { name: 'Sugar Rush', id: 4060, provider: 'Pragmatic Play' },
  { name: "Lucky Lady's Charm Deluxe", id: 64, provider: 'Novomatic Deluxe' },
  { name: 'Dead or Alive 2', id: 1084, provider: 'NetEnt' },
  { name: 'Starburst', id: 1008, provider: 'NetEnt' },
  { name: 'Dancing Joker', id: 6000, provider: '3 Oaks Gaming' },
  { name: 'Coin Express', id: 6001, provider: '3 Oaks Gaming' },
  { name: 'Big Heist', id: 6002, provider: '3 Oaks Gaming' },
  { name: "Jammin' Jars", id: 5008, provider: 'Push Gaming' },
  { name: 'Book of Ra Deluxe', id: 13, provider: 'Novomatic Deluxe' },
  { name: 'Reactoonz', id: 3022, provider: 'PlaynGO' },
  { name: "Gonzo's Quest", id: 1007, provider: 'NetEnt' },
  { name: 'Sweet Bonanza', id: 4029, provider: 'Pragmatic Play' },
  { name: 'Big Bamboo', id: 5032, provider: 'Push Gaming' },
  { name: 'Sizzling Hot Deluxe', id: 92, provider: 'Novomatic Deluxe' },
  { name: 'Book of Dead', id: 3004, provider: 'PlaynGO' },
];

export const BETINHELL_GAME_NAMES_WITH_IDS: GameData[] = [
  { name: 'Book Of Sunrise', id: 533 },
  { name: 'Frozen Rich Joker', id: 536 },
  { name: 'Book Of Dark Sun', id: 534 },
  { name: "Cleopatra's Diary", id: 521 },
  { name: 'Joker Win Spin', id: 537 },
  { name: 'Deep Blue Sea', id: 519 },
  { name: 'Treasure of Shaman', id: 500 },
  { name: 'Divine Carnival', id: 523 },
  { name: 'Gemstone Of Aztec', id: 508 },
  { name: 'Horror Castle', id: 511 },
  { name: 'Super Hamster', id: 518 },
  { name: 'Goblins Land', id: 509 },
  { name: 'Don Slottione', id: 524 },
  { name: 'Lapland', id: 505 },
  { name: 'Cheerful farmer', id: 506 },
  { name: 'Space Battle', id: 510 },
  { name: 'Sweet paradise', id: 501 },
  { name: 'Evil Genotype', id: 514 },
  { name: 'Revenge of cyborgs', id: 513 },
  { name: 'Sea underwater club', id: 503 },
  { name: 'Maniac house', id: 502 },
  { name: 'Forest ant', id: 504 },
  { name: 'Joker Strike Again', id: 531 },
  { name: 'Book Of Sahara', id: 532 },
  { name: 'Romance V', id: 529 },
  { name: 'The Sword & The Magic', id: 530 },
  { name: 'Imhotep Manuscript', id: 520 },
  { name: "Warlock's Book", id: 516 },
  { name: 'Wild Rodeo', id: 515 },
  { name: 'Brave Mongoose', id: 512 },
  { name: 'Spin Joker Spin', id: 522 },
  { name: 'Resident 3D', id: 517 },
  { name: 'Gates Of Hell', id: 507 },
];

export const PLAYTECH_GAME_NAMES_WITH_IDS: GameData[] = [
  { name: 'Azteca', id: 4 },
  { name: 'New Year Girls', id: 74 },
  { name: 'Nights', id: 75 },
  { name: 'Rome & Glory', id: 84 },
  { name: 'Viking Striking', id: 100 },
  { name: 'Riddle Jungle', id: 82 },
  { name: 'Thai Paradise', id: 97 },
  { name: 'World Travel', id: 102 },
  { name: 'Cute And Fluffy', id: 22 },
  { name: 'Le Comte de Monte Cristo', id: 60 },
  { name: 'New Space Adventure', id: 73 },
  { name: "Captain's Treasure Pro", id: 14 },
  { name: 'Pirates Slots', id: 78 },
  { name: 'Rockabilly', id: 83 },
];
