export interface GameData {
  name: string;
  id: number;
  provider?: string;
}

export const GAMINATOR_GAME_NAMES_WITH_IDS = [
  { name: 'Always Hot', id: 1, provider: 'superomatic' },
  { name: 'Bananas Go Bahamas', id: 2, provider: 'superomatic' },
  { name: 'Beetle Mania', id: 3, provider: 'superomatic' },
  { name: 'Book Of Ra', id: 4, provider: 'superomatic' },
  { name: 'Venetian Carnival', id: 5, provider: 'superomatic' },
  { name: 'Columbus', id: 6, provider: 'superomatic' },
  { name: "Dolphin's Pearl", id: 7, provider: 'superomatic' },
  { name: 'Hot Target', id: 8, provider: 'superomatic' },
  { name: 'Just Jewels', id: 9, provider: 'superomatic' },
  { name: "Lucky Lady's Charm", id: 10, provider: 'superomatic' },
  { name: 'Magic Money', id: 11, provider: 'superomatic' },
  { name: 'Marco Polo', id: 12, provider: 'superomatic' },
  { name: 'The Money Game', id: 13, provider: 'superomatic' },
  { name: "Oliver's Bar", id: 14, provider: 'superomatic' },
  { name: 'Pharaons Gold II', id: 15, provider: 'superomatic' },
  { name: 'Queen Of Hearts', id: 16, provider: 'superomatic' },
  { name: 'Riches Of India', id: 17, provider: 'superomatic' },
  { name: 'Roller Coaster', id: 18, provider: 'superomatic' },
  { name: 'Sharky', id: 19, provider: 'superomatic' },
  { name: 'Sizzing Hot', id: 20, provider: 'superomatic' },
  { name: 'Ultra Hot', id: 21, provider: 'superomatic' },
  { name: 'Unicorn Magic', id: 22, provider: 'superomatic' },
  { name: 'Aztec Gold', id: 23, provider: 'superomatic' },
  { name: 'Cash Machine', id: 24, provider: 'superomatic' },
  { name: 'Cleopatra Gold', id: 25, provider: 'superomatic' },
  { name: 'Crazy Traffic', id: 26, provider: 'superomatic' },
  { name: 'Da Vinci Diamonds', id: 27, provider: 'superomatic' },
  { name: 'Golds Fever', id: 28, provider: 'superomatic' },
  { name: 'Knights Of The Grail', id: 29, provider: 'superomatic' },
  { name: 'Monopoly', id: 30, provider: 'superomatic' },
  { name: 'Mystics Adventure', id: 31, provider: 'superomatic' },
  { name: "Pharaon's Treasure", id: 32, provider: 'superomatic' },
  { name: 'Russian Treasure', id: 33, provider: 'superomatic' },
  { name: 'Sultan Castle', id: 34, provider: 'superomatic' },
  { name: 'Treasure Castle', id: 35, provider: 'superomatic' },
  { name: 'Vegas Babe', id: 36, provider: 'superomatic' },
  { name: 'Brazilian Beauty', id: 37, provider: 'superomatic' },
  { name: 'Pirates Gold', id: 38, provider: 'superomatic' },
  { name: 'River Belle', id: 39, provider: 'superomatic' },
  { name: 'Chinese Gate Treasure', id: 40, provider: 'superomatic' },
  { name: 'Crushin', id: 41, provider: 'superomatic' },
  { name: 'Cuba Libre', id: 42, provider: 'superomatic' },
  { name: 'Deep Water Fishing', id: 43, provider: 'superomatic' },
  { name: "Pharaoh's Gold 2", id: 44, provider: 'superomatic' },
  { name: 'Faust', id: 45, provider: 'superomatic' },
  { name: 'Kilimanjaro Treasure', id: 46, provider: 'superomatic' },
  { name: 'Magic Cash', id: 47, provider: 'superomatic' },
  { name: 'Riches Of India', id: 48, provider: 'superomatic' },
  { name: 'Ronin', id: 49, provider: 'superomatic' },
  { name: 'Secret Of Temptation', id: 50, provider: 'superomatic' },
  { name: 'Zeus', id: 51, provider: 'superomatic' },
  { name: 'Indiana Jones Adventure', id: 52, provider: 'superomatic' },
  { name: 'Bush Explorer', id: 53, provider: 'superomatic' },
  { name: "D'Artagnan", id: 54, provider: 'superomatic' },
  { name: 'Strip Tease', id: 55, provider: 'superomatic' },
  { name: 'Gold Spell', id: 56, provider: 'superomatic' },
  { name: 'Midnight', id: 57, provider: 'superomatic' },
  { name: 'Lord Of The Ocean', id: 58, provider: 'superomatic' },
];

export const GAMINATOR2_GAME_NAMES_WITH_IDS = [
  { name: 'Dianas Realm', id: 59, provider: 'superomatic' },
  { name: 'Four Queens', id: 60, provider: 'superomatic' },
  { name: 'Lions', id: 61, provider: 'superomatic' },
  { name: 'Tiki Island', id: 62, provider: 'superomatic' },
  { name: 'Waikiki Beach', id: 63, provider: 'superomatic' },
  { name: 'Pharaohs Gold III', id: 64, provider: 'superomatic' },
  { name: 'Dynasty Of Ming', id: 65, provider: 'superomatic' },
  { name: 'Royal Treasures', id: 66, provider: 'superomatic' },
  { name: 'Wonderful Flute', id: 67, provider: 'superomatic' },
  { name: 'Polar Fox', id: 68, provider: 'superomatic' },
  { name: 'Banana Splash', id: 69, provider: 'superomatic' },
  { name: 'Attila', id: 70, provider: 'superomatic' },
  { name: "Buzzzin' Bugs", id: 71, provider: 'superomatic' },
  { name: 'Columbus Deluxe', id: 72, provider: 'superomatic' },
  { name: 'First Class Traveler', id: 73, provider: 'superomatic' },
  { name: 'Golden Planet', id: 74, provider: 'superomatic' },
  { name: 'Holmes Watson', id: 75, provider: 'superomatic' },
  { name: 'Secret Forest', id: 76, provider: 'superomatic' },
  { name: 'Glyphons Gold', id: 77, provider: 'superomatic' },
  { name: 'Kings Of Cash', id: 78, provider: 'superomatic' },
  { name: 'Treasure Diver', id: 79, provider: 'superomatic' },
  { name: 'Illusionist', id: 80, provider: 'superomatic' },
  { name: 'Piramid Of Secrets', id: 101, provider: 'superomatic' },
  { name: 'Sky Masters', id: 102, provider: 'superomatic' },
  { name: 'Sushi Roulette', id: 103, provider: 'superomatic' },
  { name: 'Burning Hot Admiral', id: 104, provider: 'superomatic' },
  { name: 'Burning Target Admiral', id: 105, provider: 'superomatic' },
  { name: "Emperor's China", id: 106, provider: 'superomatic' },
  { name: 'Hat Trick', id: 107, provider: 'superomatic' },
  { name: 'Hot Party', id: 108, provider: 'superomatic' },
  { name: 'Jewels 4 All', id: 109, provider: 'superomatic' },
  { name: 'Knights And Dragons', id: 110, provider: 'superomatic' },
  { name: 'Sizzling Hot Admiral', id: 111, provider: 'superomatic' },
  { name: 'Star Attraction', id: 112, provider: 'superomatic' },
  { name: 'Treasure Jewels', id: 113, provider: 'superomatic' },
  { name: 'Ultra Hot Admiral', id: 114, provider: 'superomatic' },
  { name: 'Exotic Fruits', id: 115, provider: 'superomatic' },
  { name: 'Crazy Monkey', id: 116, provider: 'superomatic' },
  { name: "Cupid's Arrow", id: 117, provider: 'superomatic' },
  { name: 'Golden Rings', id: 118, provider: 'superomatic' },
  { name: 'Russian Fairytale', id: 119, provider: 'superomatic' },
  { name: 'Fruit Cocktail', id: 120, provider: 'superomatic' },
];

export const GAMINATOREROTIC_GAME_NAMES_WITH_IDS = [
  { name: 'Australian Women', id: 121, provider: 'superomatic' },
  { name: 'Blazin Asians', id: 122, provider: 'superomatic' },
  { name: 'Charming Girls', id: 123, provider: 'superomatic' },
  { name: 'Crazy Party', id: 124, provider: 'superomatic' },
  { name: 'Delicious Desires', id: 125, provider: 'superomatic' },
  { name: 'Erotic World', id: 126, provider: 'superomatic' },
  { name: 'Fancy Chicks', id: 127, provider: 'superomatic' },
  { name: 'Favourite Things', id: 128, provider: 'superomatic' },
  { name: 'Girls + Girls', id: 129, provider: 'superomatic' },
  { name: 'Girls Of Dream', id: 130, provider: 'superomatic' },
  { name: 'Happy Holidays', id: 131, provider: 'superomatic' },
  { name: 'Latex Style', id: 132, provider: 'superomatic' },
  { name: 'Latin Ladies', id: 133, provider: 'superomatic' },
  { name: 'Mega Boobs', id: 134, provider: 'superomatic' },
  { name: 'Naked Beauties', id: 135, provider: 'superomatic' },
  { name: 'Queens Of Strip', id: 136, provider: 'superomatic' },
  { name: 'Red Hot', id: 137, provider: 'superomatic' },
  { name: 'Shocking Blondes', id: 138, provider: 'superomatic' },
  { name: 'Stockings Cool', id: 139, provider: 'superomatic' },
  { name: 'Tasty Flavors', id: 140, provider: 'superomatic' },
  { name: 'Tits For Play', id: 141, provider: 'superomatic' },
  { name: 'Chica Boom', id: 142, provider: 'superomatic' },
  { name: 'Do Me Right', id: 143, provider: 'superomatic' },
];

export const WAZDAN_GAME_NAMES_WITH_IDS = [
  { id: 144, name: 'Black Horse', provider: 'superomatic' },
  { id: 145, name: 'Magic Target', provider: 'superomatic' },
  { id: 146, name: 'Magic Fruits', provider: 'superomatic' },
  { id: 147, name: 'Magic Fruits 81', provider: 'superomatic' },
  { id: 148, name: 'Magic Fruits 4', provider: 'superomatic' },
];

export const IGROSOFT_GAME_NAMES_WITH_IDS = [
  { id: 149, name: 'Crazy Monkey', provider: 'superomatic' },
  { id: 150, name: 'Fruit Coctail', provider: 'superomatic' },
  { id: 151, name: 'Stirlitz', provider: 'superomatic' },
  { id: 152, name: 'Fruit Coctail 2', provider: 'superomatic' },
  { id: 153, name: 'Sweet Life', provider: 'superomatic' },
  { id: 154, name: 'Sweet Life 2', provider: 'superomatic' },
  { id: 155, name: 'Gnome', provider: 'superomatic' },
  { id: 156, name: 'Bank Robbery', provider: 'superomatic' },
  { id: 157, name: 'Lucky', provider: 'superomatic' },
  { id: 158, name: 'Dragon Treasure', provider: 'superomatic' },
  { id: 159, name: 'Rock Climber', provider: 'superomatic' },
  { id: 160, name: 'Garage II', provider: 'superomatic' },
  { id: 161, name: 'Island', provider: 'superomatic' },
  { id: 162, name: 'Keks', provider: 'superomatic' },
  { id: 163, name: 'Lart Du Nu', provider: 'superomatic' },
  { id: 164, name: 'Piratos', provider: 'superomatic' },
  { id: 165, name: 'Whisky', provider: 'superomatic' },
  { id: 166, name: 'Fairy Land', provider: 'superomatic' },
  { id: 167, name: 'Alcatras', provider: 'superomatic' },
  { id: 168, name: 'Village Life', provider: 'superomatic' },
];

export const VENERA_GAME_NAMES_WITH_IDS = [
  { id: 169, name: 'RouletteVenera', provider: 'superomatic' },
];

export const EGT_GAME_NAMES_WITH_IDS = [
  { id: 170, name: 'Davinci Diamonds', provider: 'superomatic' },
  { id: 171, name: 'Pixies of the Forest', provider: 'superomatic' },
  { id: 172, name: 'Cleopatra', provider: 'superomatic' },
  { id: 173, name: 'Wolf Run', provider: 'superomatic' },
  { id: 174, name: 'Elephant King', provider: 'superomatic' },
  { id: 175, name: 'Lobstermania 2', provider: 'superomatic' },
];

export const NETENT_GAME_NAMES_WITH_IDS = [
  { id: 176, name: 'Dead Or Alive', provider: 'superomatic' },
  { id: 177, name: "Who's The Bride", provider: 'superomatic' },
  { id: 178, name: 'Star Burst', provider: 'superomatic' },
  { id: 179, name: 'Sweety Honey Fruity', provider: 'superomatic' },
  { id: 180, name: 'Twin Spin', provider: 'superomatic' },
];
