export interface GameData {
  name: string;
  id: number;
  provider?: string;
}

export const GAMINATOR_GAME_NAMES_WITH_IDS = [
  { name: 'Always Hot', id: 1, provider: 'superomatic' },
  { name: 'Bananas Go Bahamas', id: 2, provider: 'superomatic' },
  { name: 'Beetle Mania', id: 3, provider: 'superomatic' },
  { name: 'Book Of Ra', id: 4, provider: 'superomatic' },
  { name: 'Venetian Carnival', id: 5, provider: 'superomatic' },
  { name: 'Columbus', id: 6, provider: 'superomatic' },
  { name: "Dolphin's Pearl", id: 7, provider: 'superomatic' },
  { name: 'Hot Target', id: 8, provider: 'superomatic' },
  { name: 'Just Jewels', id: 9, provider: 'superomatic' },
  { name: "Lucky Lady's Charm", id: 10, provider: 'superomatic' },
  { name: 'Magic Money', id: 11, provider: 'superomatic' },
  { name: 'Marco Polo', id: 12, provider: 'superomatic' },
  { name: 'The Money Game', id: 13, provider: 'superomatic' },
  { name: "Oliver's Bar", id: 14, provider: 'superomatic' },
  { name: 'Pharaons Gold II', id: 15, provider: 'superomatic' },
  { name: 'Queen Of Hearts', id: 16, provider: 'superomatic' },
  { name: 'Riches Of India', id: 17, provider: 'superomatic' },
  { name: 'Roller Coaster', id: 18, provider: 'superomatic' },
  { name: 'Sharky', id: 19, provider: 'superomatic' },
  { name: 'Sizzing Hot', id: 20, provider: 'superomatic' },
  { name: 'Ultra Hot', id: 21, provider: 'superomatic' },
  { name: 'Unicorn Magic', id: 22, provider: 'superomatic' },
  { name: 'Aztec Gold', id: 23, provider: 'superomatic' },
  { name: 'Cash Machine', id: 24, provider: 'superomatic' },
  { name: 'Cleopatra Gold', id: 25, provider: 'superomatic' },
  { name: 'Crazy Traffic', id: 26, provider: 'superomatic' },
  { name: 'Da Vinci Diamonds', id: 27, provider: 'superomatic' },
  { name: 'Golds Fever', id: 28, provider: 'superomatic' },
  { name: 'Knights Of The Grail', id: 29, provider: 'superomatic' },
  { name: 'Monopoly', id: 30, provider: 'superomatic' },
  { name: 'Mystics Adventure', id: 31, provider: 'superomatic' },
  { name: "Pharaon's Treasure", id: 32, provider: 'superomatic' },
  { name: 'Russian Treasure', id: 33, provider: 'superomatic' },
  { name: 'Sultan Castle', id: 34, provider: 'superomatic' },
  { name: 'Treasure Castle', id: 35, provider: 'superomatic' },
  { name: 'Vegas Babe', id: 36, provider: 'superomatic' },
  { name: 'Brazilian Beauty', id: 37, provider: 'superomatic' },
  { name: 'Pirates Gold', id: 38, provider: 'superomatic' },
  { name: 'River Belle', id: 39, provider: 'superomatic' },
  { name: 'Chinese Gate Treasure', id: 40, provider: 'superomatic' },
  { name: 'Crushin', id: 41, provider: 'superomatic' },
  { name: 'Cuba Libre', id: 42, provider: 'superomatic' },
  { name: 'Deep Water Fishing', id: 43, provider: 'superomatic' },
  { name: "Pharaoh's Gold 2", id: 44, provider: 'superomatic' },
  { name: 'Faust', id: 45, provider: 'superomatic' },
  { name: 'Kilimanjaro Treasure', id: 46, provider: 'superomatic' },
  { name: 'Magic Cash', id: 47, provider: 'superomatic' },
  { name: 'Riches Of India', id: 48, provider: 'superomatic' },
  { name: 'Ronin', id: 49, provider: 'superomatic' },
  { name: 'Secret Of Temptation', id: 50, provider: 'superomatic' },
  { name: 'Zeus', id: 51, provider: 'superomatic' },
  { name: 'Indiana Jones Adventure', id: 52, provider: 'superomatic' },
  { name: 'Bush Explorer', id: 53, provider: 'superomatic' },
  { name: "D'Artagnan", id: 54, provider: 'superomatic' },
  { name: 'Strip Tease', id: 55, provider: 'superomatic' },
  { name: 'Gold Spell', id: 56, provider: 'superomatic' },
  { name: 'Midnight', id: 57, provider: 'superomatic' },
  { name: 'Lord Of The Ocean', id: 58, provider: 'superomatic' },
];

export const GAMINATOR2_GAME_NAMES_WITH_IDS = [
  { name: 'Dianas Realm', id: 59, provider: 'superomatic' },
  { name: 'Four Queens', id: 60, provider: 'superomatic' },
  { name: 'Lions', id: 61, provider: 'superomatic' },
  { name: 'Tiki Island', id: 62, provider: 'superomatic' },
  { name: 'Waikiki Beach', id: 63, provider: 'superomatic' },
  { name: 'Pharaohs Gold III', id: 64, provider: 'superomatic' },
  { name: 'Dynasty Of Ming', id: 65, provider: 'superomatic' },
  { name: 'Royal Treasures', id: 66, provider: 'superomatic' },
  { name: 'Wonderful Flute', id: 67, provider: 'superomatic' },
  { name: 'Polar Fox', id: 68, provider: 'superomatic' },
  { name: 'Banana Splash', id: 69, provider: 'superomatic' },
  { name: 'Attila', id: 70, provider: 'superomatic' },
  { name: "Buzzzin' Bugs", id: 71, provider: 'superomatic' },
  { name: 'Columbus Deluxe', id: 72, provider: 'superomatic' },
  { name: 'First Class Traveler', id: 73, provider: 'superomatic' },
  { name: 'Golden Planet', id: 74, provider: 'superomatic' },
  { name: 'Holmes Watson', id: 75, provider: 'superomatic' },
  { name: 'Secret Forest', id: 76, provider: 'superomatic' },
  { name: 'Glyphons Gold', id: 77, provider: 'superomatic' },
  { name: 'Kings Of Cash', id: 78, provider: 'superomatic' },
  { name: 'Treasure Diver', id: 79, provider: 'superomatic' },
  { name: 'Illusionist', id: 80, provider: 'superomatic' },
  { name: 'Piramid Of Secrets', id: 101, provider: 'superomatic' },
  { name: 'Sky Masters', id: 102, provider: 'superomatic' },
  { name: 'Sushi Roulette', id: 103, provider: 'superomatic' },
  { name: 'Burning Hot Admiral', id: 104, provider: 'superomatic' },
  { name: 'Burning Target Admiral', id: 105, provider: 'superomatic' },
  { name: "Emperor's China", id: 106, provider: 'superomatic' },
  { name: 'Hat Trick', id: 107, provider: 'superomatic' },
  { name: 'Hot Party', id: 108, provider: 'superomatic' },
  { name: 'Jewels 4 All', id: 109, provider: 'superomatic' },
  { name: 'Knights And Dragons', id: 110, provider: 'superomatic' },
  { name: 'Sizzling Hot Admiral', id: 111, provider: 'superomatic' },
  { name: 'Star Attraction', id: 112, provider: 'superomatic' },
  { name: 'Treasure Jewels', id: 113, provider: 'superomatic' },
  { name: 'Ultra Hot Admiral', id: 114, provider: 'superomatic' },
  { name: 'Exotic Fruits', id: 115, provider: 'superomatic' },
  { name: 'Crazy Monkey', id: 116, provider: 'superomatic' },
  { name: "Cupid's Arrow", id: 117, provider: 'superomatic' },
  { name: 'Golden Rings', id: 118, provider: 'superomatic' },
  { name: 'Russian Fairytale', id: 119, provider: 'superomatic' },
  { name: 'Fruit Cocktail', id: 120, provider: 'superomatic' },
];

export const GAMINATOREROTIC_GAME_NAMES_WITH_IDS = [
  { name: 'Australian Women', id: 121, provider: 'superomatic' },
  { name: 'Blazin Asians', id: 122, provider: 'superomatic' },
  { name: 'Charming Girls', id: 123, provider: 'superomatic' },
  { name: 'Crazy Party', id: 124, provider: 'superomatic' },
  { name: 'Delicious Desires', id: 125, provider: 'superomatic' },
  { name: 'Erotic World', id: 126, provider: 'superomatic' },
  { name: 'Fancy Chicks', id: 127, provider: 'superomatic' },
  { name: 'Favourite Things', id: 128, provider: 'superomatic' },
  { name: 'Girls + Girls', id: 129, provider: 'superomatic' },
  { name: 'Girls Of Dream', id: 130, provider: 'superomatic' },
  { name: 'Happy Holidays', id: 131, provider: 'superomatic' },
  { name: 'Latex Style', id: 132, provider: 'superomatic' },
  { name: 'Latin Ladies', id: 133, provider: 'superomatic' },
  { name: 'Mega Boobs', id: 134, provider: 'superomatic' },
  { name: 'Naked Beauties', id: 135, provider: 'superomatic' },
  { name: 'Queens Of Strip', id: 136, provider: 'superomatic' },
  { name: 'Red Hot', id: 137, provider: 'superomatic' },
  { name: 'Shocking Blondes', id: 138, provider: 'superomatic' },
  { name: 'Stockings Cool', id: 139, provider: 'superomatic' },
  { name: 'Tasty Flavors', id: 140, provider: 'superomatic' },
  { name: 'Tits For Play', id: 141, provider: 'superomatic' },
  { name: 'Chica Boom', id: 142, provider: 'superomatic' },
  { name: 'Do Me Right', id: 143, provider: 'superomatic' },
];

export const WAZDAN_GAME_NAMES_WITH_IDS = [
  { id: 144, name: 'Black Horse', provider: 'superomatic' },
  { id: 145, name: 'Magic Target', provider: 'superomatic' },
  { id: 146, name: 'Magic Fruits', provider: 'superomatic' },
  { id: 147, name: 'Magic Fruits 81', provider: 'superomatic' },
  { id: 148, name: 'Magic Fruits 4', provider: 'superomatic' },
];

export const IGROSOFT_GAME_NAMES_WITH_IDS = [
  { id: 149, name: 'Crazy Monkey', provider: 'superomatic' },
  { id: 150, name: 'Fruit Coctail', provider: 'superomatic' },
  { id: 151, name: 'Stirlitz', provider: 'superomatic' },
  { id: 152, name: 'Fruit Coctail 2', provider: 'superomatic' },
  { id: 153, name: 'Sweet Life', provider: 'superomatic' },
  { id: 154, name: 'Sweet Life 2', provider: 'superomatic' },
  { id: 155, name: 'Gnome', provider: 'superomatic' },
  { id: 156, name: 'Bank Robbery', provider: 'superomatic' },
  { id: 157, name: 'Lucky', provider: 'superomatic' },
  { id: 158, name: 'Dragon Treasure', provider: 'superomatic' },
  { id: 159, name: 'Rock Climber', provider: 'superomatic' },
  { id: 160, name: 'Garage II', provider: 'superomatic' },
  { id: 161, name: 'Island', provider: 'superomatic' },
  { id: 162, name: 'Keks', provider: 'superomatic' },
  { id: 163, name: 'Lart Du Nu', provider: 'superomatic' },
  { id: 164, name: 'Piratos', provider: 'superomatic' },
  { id: 165, name: 'Whisky', provider: 'superomatic' },
  { id: 166, name: 'Fairy Land', provider: 'superomatic' },
  { id: 167, name: 'Alcatras', provider: 'superomatic' },
  { id: 168, name: 'Village Life', provider: 'superomatic' },
];

export const VENERA_GAME_NAMES_WITH_IDS = [
  { id: 169, name: 'RouletteVenera', provider: 'superomatic' },
];

export const IGT_GAME_NAMES_WITH_IDS = [
  { id: 170, name: 'Davinci Diamonds', provider: 'superomatic' },
  { id: 171, name: 'Pixies of the Forest', provider: 'superomatic' },
  { id: 172, name: 'Cleopatra', provider: 'superomatic' },
  { id: 173, name: 'Wolf Run', provider: 'superomatic' },
  { id: 174, name: 'Elephant King', provider: 'superomatic' },
  { id: 175, name: 'Lobstermania 2', provider: 'superomatic' },
  { id: 186, name: 'Arctic Fox', provider: 'superomatic' },
  { id: 187, name: 'Cat Paws', provider: 'superomatic' },
  { id: 188, name: 'Day Of The Dead', provider: 'superomatic' },
  { id: 189, name: 'Diamond Queen', provider: 'superomatic' },
  { id: 190, name: 'Dragon Dance', provider: 'superomatic' },
  { id: 191, name: 'El Gran Festival', provider: 'superomatic' },
  { id: 192, name: 'Kilimanjaro', provider: 'superomatic' },
  { id: 193, name: '100 Ladies', provider: 'superomatic' },
  { id: 194, name: 'Lady Swan', provider: 'superomatic' },
  { id: 195, name: 'Prowling Panther', provider: 'superomatic' },
  { id: 196, name: 'Savanna', provider: 'superomatic' },
  { id: 197, name: 'Sham Rockers', provider: 'superomatic' },
  { id: 198, name: 'Treasures Of The Pyramids', provider: 'superomatic' },
];

export const NETENT_BY_SUPEROMATIC_GAME_NAMES_WITH_IDS = [
  { id: 176, name: 'Dead Or Alive', provider: 'superomatic' },
  { id: 177, name: "Who's The Bride", provider: 'superomatic' },
  { id: 178, name: 'Star Burst', provider: 'superomatic' },
  { id: 179, name: 'Sweety Honey Fruity', provider: 'superomatic' },
  { id: 180, name: 'Twin Spin', provider: 'superomatic' },
  { id: 181, name: 'Spinsane', provider: 'superomatic' },
  { id: 182, name: 'Pirate from the East', provider: 'superomatic' },
  { id: 183, name: 'Twin Happiness', provider: 'superomatic' },
  { id: 184, name: 'Victorious MAX', provider: 'superomatic' },
  { id: 185, name: 'Bollywood Story', provider: 'superomatic' },
];

export const GREENTUBE_GAME_NAMES_WITH_IDS = [
  { id: 199, name: 'Reel King', provider: 'superomatic' },
  { id: 200, name: 'The Royals', provider: 'superomatic' },
  { id: 201, name: 'Book Of Ra', provider: 'superomatic' },
];

export const GAMINATOR_INT_GAME_NAMES_WITH_IDS = [
  { id: 202, name: 'Bananas Interactive', provider: 'superomatic' },
  { id: 203, name: 'Book Of Ra Interactive', provider: 'superomatic' },
  { id: 204, name: 'Columbus Interactive', provider: 'superomatic' },
  { id: 205, name: 'Hot Target Interactive', provider: 'superomatic' },
  { id: 206, name: 'Just Jewels Interactive', provider: 'superomatic' },
  { id: 207, name: 'Marco Polo Interactive', provider: 'superomatic' },
  { id: 208, name: 'Money Game Interactive', provider: 'superomatic' },
  { id: 209, name: 'Sultan Castle Interactive', provider: 'superomatic' },
  { id: 210, name: 'Vegas Babe Interactive', provider: 'superomatic' },
  { id: 211, name: 'Fruit Party', provider: 'superomatic' },
  { id: 212, name: "Life's A Beach", provider: 'superomatic' },
  { id: 213, name: 'Crazy Traffic Interactive', provider: 'superomatic' },
  { id: 214, name: 'Gold Spell Interactive', provider: 'superomatic' },
  { id: 215, name: "Lucky Lady's Charm Interactive", provider: 'superomatic' },
  { id: 216, name: "Pharaoh's Gold II Interactive", provider: 'superomatic' },
  { id: 217, name: 'Queen Of Hearts Interactive', provider: 'superomatic' },
  { id: 218, name: "D'Artagnan Interactive", provider: 'superomatic' },
  { id: 219, name: "Oliver's Bar Interactive", provider: 'superomatic' },
  { id: 220, name: 'Aztec Gold Interactive', provider: 'superomatic' },
  { id: 221, name: 'Cash Machine Interactive', provider: 'superomatic' },
  { id: 222, name: 'Fairy Land', provider: 'superomatic' },
  { id: 223, name: 'Beetle Mania Interactive', provider: 'superomatic' },
  { id: 224, name: 'Knights Of The Grail Interactive', provider: 'superomatic' },
  { id: 225, name: 'Roller Coaster Interactive', provider: 'superomatic' },
  { id: 226, name: 'Venetian Carnival Interactive', provider: 'superomatic' },
  { id: 227, name: 'Magic Money Interactive', provider: 'superomatic' },
  { id: 228, name: 'Monopoly Interactive', provider: 'superomatic' },
  { id: 229, name: "Pharaon's Treasure Interactive", provider: 'superomatic' },
  { id: 230, name: 'Russian Treasure Interactive', provider: 'superomatic' },
  { id: 231, name: 'Spicy Pizza', provider: 'superomatic' },
  { id: 232, name: 'Dolphin Tale', provider: 'superomatic' },
  { id: 233, name: 'Muchos Grande', provider: 'superomatic' },
  { id: 234, name: 'Devils Luck', provider: 'superomatic' },
  { id: 235, name: 'Boogie Monsters', provider: 'superomatic' },
  { id: 236, name: 'Sizzing Hot Interactive', provider: 'superomatic' },
  { id: 237, name: 'Pirates Gold Interactive', provider: 'superomatic' },
  { id: 238, name: 'Unicorn Magic Interactive', provider: 'superomatic' },
  { id: 239, name: 'Treasure Castle Interactive', provider: 'superomatic' },
  { id: 240, name: 'Riches Of India Interactive', provider: 'superomatic' },
  { id: 241, name: 'Sharky Interactive', provider: 'superomatic' },
  { id: 242, name: "Alladin's Wishes", provider: 'superomatic' },
  { id: 243, name: 'Fantasy Fortune', provider: 'superomatic' },
  { id: 244, name: 'Gold Fever Interactive', provider: 'superomatic' },
  { id: 245, name: 'Scoop The Cash', provider: 'superomatic' },
  { id: 246, name: 'Indiana Jones Interactive', provider: 'superomatic' },
  { id: 247, name: 'Astro', provider: 'superomatic' },
  { id: 248, name: 'Wasabi-San', provider: 'superomatic' },
  { id: 249, name: 'Davinci Diamonds Interactive', provider: 'superomatic' },
  { id: 250, name: 'LuckyFlowers', provider: 'superomatic' },
  { id: 251, name: 'Beer Fest', provider: 'superomatic' },
  { id: 252, name: 'Bust Safe', provider: 'superomatic' },
];

export const APOLLO_GAME_NAMES_WITH_IDS = [
  { id: 253, name: 'Blood', provider: 'superomatic' },
  { id: 254, name: 'Bonus Joker II', provider: 'superomatic' },
  { id: 255, name: 'Dice81', provider: 'superomatic' },
  { id: 256, name: 'Mystery Joker II', provider: 'superomatic' },
  { id: 257, name: 'Smiling Joker II', provider: 'superomatic' },
  { id: 258, name: 'Horror Joker', provider: 'superomatic' },
  { id: 259, name: 'Burning Dice', provider: 'superomatic' },
  { id: 260, name: 'Wooden Fruits', provider: 'superomatic' },
  { id: 261, name: 'Atlantis', provider: 'superomatic' },
  { id: 262, name: 'Wild Fruits 27', provider: 'superomatic' },
  { id: 263, name: 'Horus Eye', provider: 'superomatic' },
  { id: 264, name: 'Jewel Fruits', provider: 'superomatic' },
  { id: 265, name: 'Eldorado Treasure', provider: 'superomatic' },
  { id: 266, name: 'Hell', provider: 'superomatic' },
  { id: 267, name: 'War Of The Titans', provider: 'superomatic' },
  { id: 268, name: 'Rur', provider: 'superomatic' },
  { id: 269, name: 'Lucky 81', provider: 'superomatic' },
  { id: 270, name: 'Turbo Slots', provider: 'superomatic' },
  { id: 271, name: 'Midnight Fruits 81', provider: 'superomatic' },
  { id: 272, name: 'Pandora', provider: 'superomatic' },
  { id: 273, name: 'RichFish', provider: 'superomatic' },
  { id: 274, name: 'MagicLady', provider: 'superomatic' },
  { id: 275, name: 'Gangster World', provider: 'superomatic' },
  { id: 276, name: 'Mad Mechanic Deluxe', provider: 'superomatic' },
  { id: 277, name: 'Four Fruits 2', provider: 'superomatic' },
  { id: 278, name: 'Slot Birds', provider: 'superomatic' },
];

export const MEGAJACK_GAME_NAMES_WITH_IDS = [
  { id: 279, name: 'Aztec Gold', provider: 'superomatic' },
  { id: 280, name: 'Aztec Gold 2', provider: 'superomatic' },
  { id: 281, name: 'Aztec Pyramid', provider: 'superomatic' },
  { id: 282, name: 'Sizzling Girls', provider: 'superomatic' },
  { id: 283, name: 'Corsair Treasure', provider: 'superomatic' },
  { id: 284, name: 'Slot-O-Pol', provider: 'superomatic' },
  { id: 285, name: 'Slot-O-Pol Deluxe', provider: 'superomatic' },
  { id: 286, name: 'Champagne', provider: 'superomatic' },
  { id: 287, name: 'Slot-So-Cool', provider: 'superomatic' },
  { id: 288, name: 'Circus Fortune', provider: 'superomatic' },
  { id: 289, name: 'Slot-So-Cool Deluxe', provider: 'superomatic' },
  { id: 290, name: 'Devil Deluxe', provider: 'superomatic' },
  { id: 291, name: 'Sparkling', provider: 'superomatic' },
  { id: 292, name: 'Wildest', provider: 'superomatic' },
];

export const VIDEO_GAME_NAMES_WITH_IDS = [
  { id: 293, name: 'Gladiator', provider: 'superomatic' },
  { id: 294, name: 'Hobbit', provider: 'superomatic' },
  { id: 295, name: 'John Carter', provider: 'superomatic' },
  { id: 296, name: 'Playboy', provider: 'superomatic' },
  { id: 297, name: 'Show Girls', provider: 'superomatic' },
  { id: 298, name: 'Avengers', provider: 'superomatic' },
  { id: 299, name: 'Sweet Hot', provider: 'superomatic' },
  { id: 300, name: 'Wreck It Ralph', provider: 'superomatic' },
];

export const FIVEXFIVE_GAME_NAMES_WITH_IDS = [
  { id: 301, name: 'Book Of Ra 5x5', provider: 'superomatic' },
  { id: 302, name: 'Galaxy Adventure', provider: 'superomatic' },
  { id: 303, name: 'Magic Story', provider: 'superomatic' },
  { id: 304, name: 'Irish Adventures', provider: 'superomatic' },
  { id: 305, name: 'Crazy Cars 5x5', provider: 'superomatic' },
  { id: 306, name: 'Jungle Jim 5x5', provider: 'superomatic' },
  { id: 307, name: 'Polar Bash 5x5', provider: 'superomatic' },
  { id: 308, name: 'Bahamas Babes', provider: 'superomatic' },
  { id: 309, name: 'Great Hit', provider: 'superomatic' },
  { id: 310, name: 'Gnome 3', provider: 'superomatic' },
  { id: 311, name: 'Rock Climber 3', provider: 'superomatic' },
  { id: 312, name: 'Garage 3 5x5', provider: 'superomatic' },
  { id: 313, name: 'Eastern Tale', provider: 'superomatic' },
  { id: 314, name: 'Island 3', provider: 'superomatic' },
  { id: 315, name: 'Sweet Sweet 3', provider: 'superomatic' },
  { id: 316, name: 'Mega Frog', provider: 'superomatic' },
  { id: 317, name: 'Viking Reels', provider: 'superomatic' },
  { id: 318, name: 'Santa Gifts', provider: 'superomatic' },
  { id: 319, name: 'Witch Slot', provider: 'superomatic' },
  { id: 320, name: 'Mexicanos', provider: 'superomatic' },
  { id: 321, name: 'Piece Of Cake', provider: 'superomatic' },
  { id: 322, name: 'FishingMania', provider: 'superomatic' },
  { id: 323, name: 'Fairy Girls', provider: 'superomatic' },
  { id: 324, name: 'Vip Society', provider: 'superomatic' },
  { id: 325, name: 'Perfect Strike 5x5', provider: 'superomatic' },
  { id: 326, name: 'SimSimSlot', provider: 'superomatic' },
  { id: 327, name: 'Spark Of Love', provider: 'superomatic' },
  { id: 328, name: 'Private Eye 5x5', provider: 'superomatic' },
  { id: 329, name: 'Sharky 5x5', provider: 'superomatic' },
];

export const GLOBAL_GAME_NAMES_WITH_IDS = [
  { id: 330, name: 'Cherry Love', provider: 'superomatic' },
  { id: 331, name: 'Cute & Fluffy', provider: 'superomatic' },
  { id: 332, name: 'Discovery', provider: 'superomatic' },
  { id: 333, name: 'Fairy Magic', provider: 'superomatic' },
  { id: 334, name: 'Fantastic Four', provider: 'superomatic' },
  { id: 335, name: 'From Russia', provider: 'superomatic' },
  { id: 336, name: 'Happy Bugs', provider: 'superomatic' },
  { id: 337, name: 'House Of The Dead', provider: 'superomatic' },
  { id: 338, name: 'Penguin Vacation', provider: 'superomatic' },
  { id: 339, name: 'Phantasy Star', provider: 'superomatic' },
  { id: 340, name: 'Punisher', provider: 'superomatic' },
  { id: 341, name: 'Rocky', provider: 'superomatic' },
  { id: 342, name: 'Virtua Fighter', provider: 'superomatic' },
  { id: 343, name: 'Al Capone', provider: 'superomatic' },
  { id: 344, name: 'Azteca', provider: 'superomatic' },
  { id: 345, name: 'Diamond Valley Pro', provider: 'superomatic' },
  { id: 346, name: 'Dolphin Reef', provider: 'superomatic' },
  { id: 347, name: 'Great Blue', provider: 'superomatic' },
  { id: 348, name: 'Panter Moon', provider: 'superomatic' },
  { id: 349, name: 'Safari Heat', provider: 'superomatic' },
  { id: 350, name: 'Silent Samurai', provider: 'superomatic' },
  { id: 351, name: 'Sparta', provider: 'superomatic' },
  { id: 352, name: 'Wild Spirit', provider: 'superomatic' },
  { id: 353, name: 'Pharaohs Secrets', provider: 'superomatic' },
  { id: 354, name: 'Arctic Treasure', provider: 'superomatic' },
  { id: 355, name: 'Bonus Bears', provider: 'superomatic' },
  { id: 356, name: 'Captain Treasure Pro', provider: 'superomatic' },
  { id: 357, name: 'Desert Treasure', provider: 'superomatic' },
  { id: 358, name: 'Golden Games', provider: 'superomatic' },
  { id: 359, name: 'Incredible Hulk', provider: 'superomatic' },
  { id: 360, name: 'Irish Luck', provider: 'superomatic' },
  { id: 361, name: 'A Night Out', provider: 'superomatic' },
  { id: 362, name: 'Nights', provider: 'superomatic' },
  { id: 363, name: 'Rome & Glory', provider: 'superomatic' },
  { id: 364, name: 'Skazka', provider: 'superomatic' },
  { id: 365, name: 'Thai Paradise', provider: 'superomatic' },
  { id: 366, name: 'True Love', provider: 'superomatic' },
  { id: 367, name: 'Incredible Hulk 50', provider: 'superomatic' },
  { id: 368, name: 'Blade', provider: 'superomatic' },
  { id: 369, name: 'Daredevil', provider: 'superomatic' },
  { id: 370, name: 'Elektra', provider: 'superomatic' },
  { id: 371, name: 'Football Rules', provider: 'superomatic' },
  { id: 372, name: 'Harry Potter', provider: 'superomatic' },
  { id: 373, name: 'La Chatte Rouge', provider: 'superomatic' },
  { id: 374, name: 'Spin2Millions', provider: 'superomatic' },
  { id: 375, name: 'Xmen', provider: 'superomatic' },
  { id: 376, name: 'Transformers', provider: 'superomatic' },
  { id: 377, name: 'Desert Treasure 2', provider: 'superomatic' },
  { id: 378, name: 'Kong', provider: 'superomatic' },
  { id: 379, name: 'Top Gun', provider: 'superomatic' },
];

export const EXCITING_GAME_NAMES_WITH_IDS = [
  { id: 380, name: 'Dodge City', provider: 'superomatic' },
  { id: 381, name: 'Dog Mafia', provider: 'superomatic' },
  { id: 382, name: 'Hot Seven', provider: 'superomatic' },
  { id: 383, name: 'London Fever', provider: 'superomatic' },
  { id: 384, name: 'Money Honey', provider: 'superomatic' },
  { id: 385, name: 'Riddle Jungle', provider: 'superomatic' },
  { id: 386, name: 'Cave Goblins', provider: 'superomatic' },
  { id: 387, name: 'Devils Night', provider: 'superomatic' },
  { id: 388, name: 'Frozen', provider: 'superomatic' },
  { id: 389, name: 'Merry Christmas', provider: 'superomatic' },
  { id: 390, name: 'New Space Adventure', provider: 'superomatic' },
  { id: 391, name: 'Royal Scotland', provider: 'superomatic' },
  { id: 392, name: 'Wild Reserve', provider: 'superomatic' },
  { id: 393, name: 'Monte Cristo', provider: 'superomatic' },
  { id: 394, name: 'Sinderella', provider: 'superomatic' },
  { id: 395, name: 'Newyear Girls', provider: 'superomatic' },
  { id: 396, name: 'Pirate Slots', provider: 'superomatic' },
  { id: 397, name: 'Rockabilly', provider: 'superomatic' },
  { id: 398, name: 'Vicing Striking', provider: 'superomatic' },
  { id: 399, name: 'World Travel', provider: 'superomatic' },
  { id: 400, name: 'Kingdom', provider: 'superomatic' },
  { id: 401, name: 'Market Mania', provider: 'superomatic' },
  { id: 402, name: 'Minotaurs Gold', provider: 'superomatic' },
  { id: 403, name: 'Beauty Parlor', provider: 'superomatic' },
  { id: 404, name: 'Candy Shop', provider: 'superomatic' },
  { id: 405, name: 'Dinner Party', provider: 'superomatic' },
  { id: 406, name: 'Dragons Nest', provider: 'superomatic' },
  { id: 407, name: 'Elven Mirror', provider: 'superomatic' },
  { id: 408, name: 'Erotic Fantasy', provider: 'superomatic' },
  { id: 409, name: 'Halloween Night', provider: 'superomatic' },
  { id: 410, name: 'Inca Treasures', provider: 'superomatic' },
  { id: 411, name: 'Jewellery Shop', provider: 'superomatic' },
  { id: 412, name: 'Magican Of The Emerald Town', provider: 'superomatic' },
  { id: 413, name: 'Prison Adventure', provider: 'superomatic' },
  { id: 414, name: 'Seasons Reels', provider: 'superomatic' },
  { id: 415, name: 'Stone Quest', provider: 'superomatic' },
  { id: 416, name: 'Summer On The Beach', provider: 'superomatic' },
  { id: 417, name: 'Sweet Surprize', provider: 'superomatic' },
  { id: 418, name: 'The Beatles', provider: 'superomatic' },
  { id: 419, name: 'World Under Water', provider: 'superomatic' },
  { id: 420, name: 'The Legend Of Zorro', provider: 'superomatic' },
];

export const IGROSOFT_INT_GAME_NAMES_WITH_IDS = [
  { id: 421, name: 'Fruit Coctail 2 Interactive', provider: 'superomatic' },
  { id: 422, name: 'Island Interactive', provider: 'superomatic' },
  { id: 423, name: 'Fairyland Interactive', provider: 'superomatic' },
  { id: 424, name: 'Crazy Hunter Interactive', provider: 'superomatic' },
  { id: 425, name: 'Garage 2 Interactive', provider: 'superomatic' },
  { id: 426, name: 'Sweet Life Interactive', provider: 'superomatic' },
  { id: 427, name: 'Fruit Cocktail Interactive', provider: 'superomatic' },
  { id: 428, name: 'Bank Robbery Interactive', provider: 'superomatic' },
  { id: 429, name: 'Crazy Monkey Interactive', provider: 'superomatic' },
  { id: 430, name: 'Dragon Treasure Interactive', provider: 'superomatic' },
  { id: 431, name: "L'Art Du Nu Interactive", provider: 'superomatic' },
  { id: 432, name: 'Piratos Interactive', provider: 'superomatic' },
  { id: 433, name: 'Rock Climber Interactive', provider: 'superomatic' },
  { id: 434, name: 'Gnome Interactive', provider: 'superomatic' },
  { id: 435, name: 'Rezident Interactive', provider: 'superomatic' },
  { id: 436, name: 'Keks Interactive', provider: 'superomatic' },
  { id: 437, name: 'Whisky Interactive', provider: 'superomatic' },
  { id: 438, name: 'Sweet Life 2 Interactive', provider: 'superomatic' },
];

export const CHAMPION_GAME_NAMES_WITH_IDS = [
  { id: 439, name: 'Nautilus', provider: 'superomatic' },
  { id: 440, name: 'Fire Frenzy', provider: 'superomatic' },
  { id: 441, name: 'Gulliver', provider: 'superomatic' },
  { id: 442, name: 'Sea Light', provider: 'superomatic' },
  { id: 443, name: 'Lucky Ladys Glamour', provider: 'superomatic' },
  { id: 444, name: 'Sevens On Fire', provider: 'superomatic' },
  { id: 445, name: 'Bananas', provider: 'superomatic' },
  { id: 446, name: 'Riddle Of The Sphinx', provider: 'superomatic' },
  { id: 447, name: 'Mariner', provider: 'superomatic' },
  { id: 448, name: 'Crazy Barmen', provider: 'superomatic' },
  { id: 449, name: 'Pirates Fortune', provider: 'superomatic' },
  { id: 450, name: 'Casino World', provider: 'superomatic' },
  { id: 451, name: 'Hot Sevens', provider: 'superomatic' },
  { id: 452, name: 'Rich Fruits', provider: 'superomatic' },
  { id: 453, name: 'Casino And Stars', provider: 'superomatic' },
  { id: 454, name: 'Money', provider: 'superomatic' },
  { id: 455, name: 'Savanna Queen', provider: 'superomatic' },
  { id: 456, name: 'Hearts', provider: 'superomatic' },
  { id: 457, name: 'Gates Of Avalon', provider: 'superomatic' },
  { id: 458, name: 'Golden Harvest', provider: 'superomatic' },
  { id: 459, name: 'Robinson', provider: 'superomatic' },
  { id: 460, name: 'Fire Rage', provider: 'superomatic' },
  { id: 461, name: 'Hot Slot', provider: 'superomatic' },
  { id: 462, name: 'Kings Of Jewels', provider: 'superomatic' },
  { id: 463, name: 'Tropical Fruit', provider: 'superomatic' },
  { id: 464, name: 'Book Of Winners', provider: 'superomatic' },
  { id: 465, name: 'Magic Secret', provider: 'superomatic' },
  { id: 466, name: 'Computer World', provider: 'superomatic' },
  { id: 467, name: 'Roll Of Ramses', provider: 'superomatic' },
  { id: 468, name: 'Scatter Wins', provider: 'superomatic' },
  { id: 469, name: 'Triple Diamond', provider: 'superomatic' },
];

export const ARISTOCRAT_GAME_NAMES_WITH_IDS = [
  { id: 470, name: 'Geisha', provider: 'superomatic' },
  { id: 471, name: 'Dolphin Treasure', provider: 'superomatic' },
  { id: 472, name: 'Queen Of The Nile', provider: 'superomatic' },
  { id: 473, name: 'Big Red', provider: 'superomatic' },
  { id: 474, name: 'Lucky Count', provider: 'superomatic' },
  { id: 475, name: '5 Dragons', provider: 'superomatic' },
  { id: 476, name: 'Tiki Torch', provider: 'superomatic' },
  { id: 477, name: 'Sun And Moon', provider: 'superomatic' },
  { id: 478, name: 'Queen Of The Nile II', provider: 'superomatic' },
  { id: 479, name: '50 Lions', provider: 'superomatic' },
  { id: 480, name: '50 Dragons', provider: 'superomatic' },
  { id: 481, name: 'Miss Kitty', provider: 'superomatic' },
  { id: 482, name: 'Moon Festival', provider: 'superomatic' },
  { id: 483, name: 'Double Happiness', provider: 'superomatic' },
  { id: 484, name: 'Buffalo', provider: 'superomatic' },
  { id: 485, name: 'Wolf Moon', provider: 'superomatic' },
  { id: 486, name: 'Were Wolf Wild', provider: 'superomatic' },
  { id: 487, name: 'Imperial House', provider: 'superomatic' },
  { id: 488, name: 'Where Is The Gold', provider: 'superomatic' },
  { id: 489, name: 'Big Ben', provider: 'superomatic' },
];

export const EGT_GAME_NAMES_WITH_IDS = [
  { id: 490, name: 'Age Of Troy', provider: 'superomatic' },
  { id: 491, name: 'Amazons Battle', provider: 'superomatic' },
  { id: 492, name: 'Blue Heart', provider: 'superomatic' },
  { id: 493, name: 'Burning Dice', provider: 'superomatic' },
  { id: 494, name: 'Burning Hot', provider: 'superomatic' },
  { id: 495, name: 'Caramel Hot', provider: 'superomatic' },
  { id: 496, name: '100 Cats', provider: 'superomatic' },
  { id: 497, name: '5 Dazzling Hot', provider: 'superomatic' },
  { id: 498, name: '20 Diamonds', provider: 'superomatic' },
  { id: 499, name: 'Dice Of Ra', provider: 'superomatic' },
  { id: 500, name: 'Dragon Reels', provider: 'superomatic' },
  { id: 501, name: 'Extra Stars', provider: 'superomatic' },
  { id: 502, name: 'Extremely Hot', provider: 'superomatic' },
  { id: 503, name: 'Flaming Hot', provider: 'superomatic' },
  { id: 504, name: 'Fruits Kingdom', provider: 'superomatic' },
  { id: 505, name: 'Game Of Luck', provider: 'superomatic' },
  { id: 506, name: 'Grace Of Cleopatra', provider: 'superomatic' },
  { id: 507, name: 'Great Egypt', provider: 'superomatic' },
  { id: 508, name: 'Great Empire', provider: 'superomatic' },
  { id: 509, name: 'Olympus Glory', provider: 'superomatic' },
  { id: 510, name: 'Secrets Of Alchemy', provider: 'superomatic' },
  { id: 511, name: 'Shining Crown', provider: 'superomatic' },
  { id: 512, name: '30 Spicy Fruits', provider: 'superomatic' },
  { id: 513, name: '100 Super Hot', provider: 'superomatic' },
  { id: 514, name: '20 Super Hot', provider: 'superomatic' },
  { id: 515, name: '40 Super Hot', provider: 'superomatic' },
  { id: 516, name: 'Supreme Hot', provider: 'superomatic' },
  { id: 517, name: 'Ultimate Hot', provider: 'superomatic' },
  { id: 518, name: 'Zodiac Wheel', provider: 'superomatic' },
  { id: 519, name: 'Amazing Amazonia', provider: 'superomatic' },
  { id: 520, name: 'Aztec Glory', provider: 'superomatic' },
  { id: 521, name: 'Book of Magic', provider: 'superomatic' },
  { id: 522, name: '10 Burning Heart', provider: 'superomatic' },
  { id: 523, name: '5 Burning Heart', provider: 'superomatic' },
  { id: 524, name: '20 Burning Hot', provider: 'superomatic' },
  { id: 525, name: 'Coral Island', provider: 'superomatic' },
  { id: 526, name: '20 Dazzling Hot', provider: 'superomatic' },
  { id: 527, name: '2 Dragons', provider: 'superomatic' },
  { id: 528, name: 'Fast Money', provider: 'superomatic' },
  { id: 529, name: 'Fortune Spells', provider: 'superomatic' },
  { id: 530, name: '5 Great Star', provider: 'superomatic' },
  { id: 531, name: '20 Joker Reels', provider: 'superomatic' },
  { id: 532, name: '40 Lucky King', provider: 'superomatic' },
  { id: 533, name: 'Majestic Forest', provider: 'superomatic' },
  { id: 534, name: 'Queen of Rio', provider: 'superomatic' },
  { id: 535, name: 'Retro Style', provider: 'superomatic' },
  { id: 536, name: 'Rise of RA', provider: 'superomatic' },
  { id: 537, name: 'Spanish Passion', provider: 'superomatic' },
  { id: 538, name: 'The Big Journey', provider: 'superomatic' },
  { id: 539, name: 'The White Wolf', provider: 'superomatic' },
  { id: 540, name: 'Versailles Gold', provider: 'superomatic' },
];

export const AMATIC_GAME_NAMES_WITH_IDS = [
  { id: 541, name: 'Admiral Nelson', provider: 'superomatic' },
  { id: 542, name: 'All Ways Fruits', provider: 'superomatic' },
  { id: 543, name: 'Bells On Fire', provider: 'superomatic' },
  { id: 544, name: 'Billyonaire', provider: 'superomatic' },
  { id: 545, name: 'Blue Dolphin', provider: 'superomatic' },
  { id: 546, name: 'Book of Aztec', provider: 'superomatic' },
  { id: 547, name: 'Book of Fortune', provider: 'superomatic' },
  { id: 548, name: 'Casanova', provider: 'superomatic' },
  { id: 549, name: 'Cool Diamonds II', provider: 'superomatic' },
  { id: 550, name: 'Diamond Cats', provider: 'superomatic' },
  { id: 551, name: 'Diamond Monkey', provider: 'superomatic' },
  { id: 552, name: 'Diamonds on Fire', provider: 'superomatic' },
  { id: 553, name: 'Dragons Pearl', provider: 'superomatic' },
  { id: 554, name: 'Fire Ice', provider: 'superomatic' },
  { id: 555, name: 'Fortunas Fruits', provider: 'superomatic' },
  { id: 556, name: 'Grand X', provider: 'superomatic' },
  { id: 557, name: 'Hot Diamonds', provider: 'superomatic' },
  { id: 558, name: 'Hot Neon', provider: 'superomatic' },
  { id: 559, name: 'Hot Scatter', provider: 'superomatic' },
  { id: 560, name: 'Hot Seven', provider: 'superomatic' },
  { id: 561, name: 'Hot Star', provider: 'superomatic' },
  { id: 562, name: 'Hot Twenty', provider: 'superomatic' },
  { id: 563, name: 'Lady Joker', provider: 'superomatic' },
  { id: 564, name: 'Lovely Lady', provider: 'superomatic' },
  { id: 565, name: 'Lucky Bells', provider: 'superomatic' },
  { id: 566, name: 'Lucky Coin', provider: 'superomatic' },
  { id: 567, name: 'Magic Forest', provider: 'superomatic' },
  { id: 568, name: 'Magic Idol', provider: 'superomatic' },
  { id: 569, name: 'Magic Owl', provider: 'superomatic' },
  { id: 570, name: "Mermaid's Gold", provider: 'superomatic' },
  { id: 571, name: 'Merry Fruits', provider: 'superomatic' },
  { id: 572, name: 'Party Time', provider: 'superomatic' },
  { id: 573, name: 'Red Chilli', provider: 'superomatic' },
  { id: 574, name: 'Tweety Birds', provider: 'superomatic' },
  { id: 575, name: 'Wild 7', provider: 'superomatic' },
  { id: 576, name: 'Wild Dragon', provider: 'superomatic' },
  { id: 577, name: 'Wolf Moon', provider: 'superomatic' },
  { id: 578, name: 'Big Panda', provider: 'superomatic' },
  { id: 579, name: 'Eye Of Ra', provider: 'superomatic' },
  { id: 580, name: 'Golden Book', provider: 'superomatic' },
  { id: 581, name: 'Wild Shark', provider: 'superomatic' },
  { id: 582, name: 'Wild Stars', provider: 'superomatic' },
];

export const ENDORPHINA_GAME_NAMES_WITH_IDS = [
  { id: 583, name: 'Fresh Fruits', provider: 'superomatic' },
  { id: 584, name: 'Hell Hot 100', provider: 'superomatic' },
  { id: 585, name: 'Hit Slot 2021', provider: 'superomatic' },
  { id: 586, name: 'Lucky Streak', provider: 'superomatic' },
  { id: 587, name: 'Lucky Streak 2', provider: 'superomatic' },
  { id: 588, name: 'Lucky Streak 3', provider: 'superomatic' },
  { id: 589, name: 'Mongol Treasures', provider: 'superomatic' },
  { id: 590, name: 'The King', provider: 'superomatic' },
  { id: 591, name: 'Ultra Fresh', provider: 'superomatic' },
  { id: 592, name: 'Book Of Santa', provider: 'superomatic' },
  { id: 593, name: 'Chance Machine 100', provider: 'superomatic' },
  { id: 594, name: 'Chance Machine 5', provider: 'superomatic' },
  { id: 595, name: 'Chance Machine 40', provider: 'superomatic' },
  { id: 596, name: 'Chance Machine 20', provider: 'superomatic' },
  { id: 597, name: 'Hit Slot 2020', provider: 'superomatic' },
  { id: 598, name: 'Lucky Dice 3', provider: 'superomatic' },
  { id: 599, name: 'Lucky Dice 2', provider: 'superomatic' },
  { id: 600, name: 'Lucky Dice', provider: 'superomatic' },
  { id: 601, name: 'Urartu', provider: 'superomatic' },
  { id: 602, name: 'Sparkling Fresh', provider: 'superomatic' },
  { id: 603, name: 'Chimney Sweep', provider: 'superomatic' },
  { id: 604, name: 'More Fresh Fruits', provider: 'superomatic' },
  { id: 605, name: 'The Emirate', provider: 'superomatic' },
  { id: 606, name: 'Aus Dem Tal', provider: 'superomatic' },
  { id: 607, name: 'Football', provider: 'superomatic' },
  { id: 608, name: 'Gems n Stones', provider: 'superomatic' },
  { id: 609, name: 'Joker Stoker', provider: 'superomatic' },
  { id: 610, name: 'Mystery Of Eldorado', provider: 'superomatic' },
  { id: 611, name: 'Windy City', provider: 'superomatic' },
  { id: 612, name: '100 Zombies', provider: 'superomatic' },
  { id: 613, name: 'Buffalo 50', provider: 'superomatic' },
  { id: 614, name: 'Diamond Chance', provider: 'superomatic' },
  { id: 615, name: 'Four Of A King', provider: 'superomatic' },
  { id: 616, name: 'Little Panda', provider: 'superomatic' },
  { id: 617, name: 'Little Panda Dice', provider: 'superomatic' },
  { id: 618, name: 'Red Cap', provider: 'superomatic' },
  { id: 619, name: 'Safari', provider: 'superomatic' },
  { id: 620, name: 'Wild Fruits', provider: 'superomatic' },
  { id: 621, name: 'Almighty Sparta', provider: 'superomatic' },
  { id: 622, name: 'Almighty Sparta Dice', provider: 'superomatic' },
  { id: 623, name: 'Ancient Troy', provider: 'superomatic' },
  { id: 624, name: 'Ancient Troy Dice', provider: 'superomatic' },
  { id: 625, name: 'Asgardians', provider: 'superomatic' },
  { id: 626, name: 'Asgardians Dice', provider: 'superomatic' },
  { id: 627, name: 'Cricket Heroes', provider: 'superomatic' },
  { id: 628, name: 'Geisha', provider: 'superomatic' },
  { id: 629, name: 'In Jazz', provider: 'superomatic' },
  { id: 630, name: 'Macarons', provider: 'superomatic' },
  { id: 631, name: 'Sugar Glider', provider: 'superomatic' },
  { id: 632, name: 'Sugar Glider Dice', provider: 'superomatic' },
  { id: 633, name: 'Hell Hot 20', provider: 'superomatic' },
  { id: 634, name: 'Hell Hot 40', provider: 'superomatic' },
  { id: 635, name: 'Book Of Oil', provider: 'superomatic' },
  { id: 636, name: 'Cash Tank', provider: 'superomatic' },
  { id: 637, name: 'Gem Blast', provider: 'superomatic' },
  { id: 638, name: 'Undines Deep', provider: 'superomatic' },
  { id: 639, name: 'Temple Cats', provider: 'superomatic' },
  { id: 640, name: 'Royal Xmass', provider: 'superomatic' },
  { id: 641, name: 'Water Tiger', provider: 'superomatic' },
  { id: 642, name: 'Chunjie', provider: 'superomatic' },
  { id: 643, name: 'Football Superstar', provider: 'superomatic' },
  { id: 644, name: 'Fruletta', provider: 'superomatic' },
  { id: 645, name: 'Gladiators', provider: 'superomatic' },
  { id: 646, name: 'Gladiators 2016', provider: 'superomatic' },
  { id: 647, name: 'Golden Ox', provider: 'superomatic' },
  { id: 648, name: 'Legendary Sumo', provider: 'superomatic' },
  { id: 649, name: 'Lucky Lands', provider: 'superomatic' },
  { id: 650, name: 'Retromania', provider: 'superomatic' },
  { id: 651, name: 'The Vampires', provider: 'superomatic' },
  { id: 652, name: 'Troll Haven', provider: 'superomatic' },
];

// B2BSlots Games
export const NETENT_BY_B2B_GAME_NAMES_WITH_IDS = [
  { id: 653, name: 'Spell Cast', provider: 'B2BSlots' },
  { id: 654, name: 'Star Burst', provider: 'B2BSlots' },
  { id: 655, name: 'Flowers Christmas', provider: 'B2BSlots' },
  { id: 656, name: 'Gonzo Quest', provider: 'B2BSlots' },
  { id: 657, name: 'Bollywood Story', provider: 'B2BSlots' },
  { id: 658, name: 'Fruit Shop Christmas', provider: 'B2BSlots' },
  { id: 659, name: 'Dead Or Alive', provider: 'B2BSlots' },
  { id: 660, name: 'Excalibur', provider: 'B2BSlots' },
  { id: 661, name: 'Reel Steal', provider: 'B2BSlots' },
  { id: 662, name: 'Mythic Maiden', provider: 'B2BSlots' },
  { id: 663, name: 'Ghost Pirates', provider: 'B2BSlots' },
  { id: 664, name: 'Fruit Spin', provider: 'B2BSlots' },
  { id: 665, name: 'Space Wars', provider: 'B2BSlots' },
  { id: 666, name: 'Wild Water', provider: 'B2BSlots' },
  { id: 667, name: 'Steam Tower', provider: 'B2BSlots' },
  { id: 668, name: 'Twin Spin', provider: 'B2BSlots' },
  { id: 669, name: 'Pyramid', provider: 'B2BSlots' },
  { id: 670, name: 'Wolf Cub', provider: 'B2BSlots' },
  { id: 671, name: 'Secret Of Atlantis', provider: 'B2BSlots' },
  { id: 672, name: 'EggOMatic', provider: 'B2BSlots' },
  { id: 673, name: 'Fire Flies', provider: 'B2BSlots' },
  { id: 674, name: 'Flowers', provider: 'B2BSlots' },
  { id: 675, name: 'Piggy Riches', provider: 'B2BSlots' },
  { id: 676, name: 'Stickers', provider: 'B2BSlots' },
  { id: 677, name: 'Fruit Shop', provider: 'B2BSlots' },
  { id: 678, name: 'Lucky Angler', provider: 'B2BSlots' },
  { id: 679, name: 'Victorious Max', provider: 'B2BSlots' },
  { id: 680, name: 'Magic Portals', provider: 'B2BSlots' },
  { id: 681, name: 'American Roulette', provider: 'B2BSlots' },
  { id: 682, name: 'European Roulette', provider: 'B2BSlots' },
  { id: 683, name: 'French Roulette', provider: 'B2BSlots' },
  { id: 684, name: 'Advanced Roulette', provider: 'B2BSlots' },
  { id: 685, name: 'Reel Rush', provider: 'B2BSlots' },
  { id: 686, name: 'Sparks', provider: 'B2BSlots' },
  { id: 687, name: 'Jack Hammer', provider: 'B2BSlots' },
  { id: 688, name: 'King Of Slots', provider: 'B2BSlots' },
  { id: 689, name: 'Jack Hammer 2', provider: 'B2BSlots' },
  { id: 690, name: 'Secrets Of Christmas', provider: 'B2BSlots' },
  { id: 691, name: 'Secret Of The Stones', provider: 'B2BSlots' },
  { id: 692, name: 'Blood Suckers', provider: 'B2BSlots' },
  { id: 693, name: 'Copy Cats', provider: 'B2BSlots' },
  { id: 694, name: 'Neon Staxx', provider: 'B2BSlots' },
  { id: 695, name: 'Twin Spin Deluxe', provider: 'B2BSlots' },
  { id: 696, name: 'Joker Pro', provider: 'B2BSlots' },
  { id: 697, name: 'Dazzle Me', provider: 'B2BSlots' },
  { id: 698, name: 'Motorhead', provider: 'B2BSlots' },
  { id: 699, name: 'Wild Wild West', provider: 'B2BSlots' },
  { id: 700, name: 'Berry Burst Max', provider: 'B2BSlots' },
  { id: 701, name: 'WildOTron 3000', provider: 'B2BSlots' },
  { id: 702, name: 'BerryBurst', provider: 'B2BSlots' },
  { id: 703, name: 'Scruffy Duck', provider: 'B2BSlots' },
  { id: 704, name: 'Hooks Heroes', provider: 'B2BSlots' },
  { id: 705, name: 'HotLine', provider: 'B2BSlots' },
  { id: 706, name: 'Dracula', provider: 'B2BSlots' },
  { id: 707, name: 'Double Stacks', provider: 'B2BSlots' },
  { id: 708, name: 'Witch Craft Academy', provider: 'B2BSlots' },
  { id: 709, name: 'Jack And Beanstalk', provider: 'B2BSlots' },
  { id: 710, name: 'Halloween Jack', provider: 'B2BSlots' },
  { id: 711, name: 'Butterfly Staxx', provider: 'B2BSlots' },
  { id: 712, name: 'Wild Bazaar', provider: 'B2BSlots' },
  { id: 713, name: 'Jingle Spin', provider: 'B2BSlots' },
  { id: 714, name: 'Vikings', provider: 'B2BSlots' },
  { id: 715, name: 'Blackjack', provider: 'B2BSlots' },
  { id: 716, name: 'Coins Of Egypt', provider: 'B2BSlots' },
  { id: 717, name: 'Jungle Spirit', provider: 'B2BSlots' },
  { id: 718, name: 'Mirror Mirror', provider: 'B2BSlots' },
  { id: 719, name: 'Hansel & Gretel', provider: 'B2BSlots' },
  { id: 720, name: 'Red Riding Hood', provider: 'B2BSlots' },
  { id: 721, name: 'Aloha', provider: 'B2BSlots' },
  { id: 722, name: 'Golden Grimoire', provider: 'B2BSlots' },
  { id: 723, name: 'European Roulette Low Limit', provider: 'B2BSlots' },
  { id: 724, name: 'Advanced Roulette Low Limit', provider: 'B2BSlots' },
  { id: 725, name: 'Pirate from the East', provider: 'B2BSlots' },
  { id: 726, name: 'Whos the Bride', provider: 'B2BSlots' },
  { id: 727, name: 'Sweety Honey Fruity', provider: 'B2BSlots' },
  { id: 728, name: 'Twin Happiness', provider: 'B2BSlots' },
  { id: 729, name: 'Magic Maid Cafe', provider: 'B2BSlots' },
  { id: 730, name: 'East Sea Dragon King', provider: 'B2BSlots' },
  { id: 731, name: 'Treasure Rain', provider: 'B2BSlots' },
  { id: 732, name: 'Long Pao', provider: 'B2BSlots' },
  { id: 733, name: 'King of 3 Kingdoms', provider: 'B2BSlots' },
  { id: 734, name: 'Wild Turkey', provider: 'B2BSlots' },
  { id: 735, name: 'Fortune Rangers', provider: 'B2BSlots' },
  { id: 736, name: 'Dead Or Alive 2', provider: 'B2BSlots' },
  { id: 737, name: 'Go Bananas', provider: 'B2BSlots' },
  { id: 738, name: 'Fruit Case', provider: 'B2BSlots' },
  { id: 739, name: 'Temple Of Nudges', provider: 'B2BSlots' },
  { id: 740, name: 'Oceans Treasure', provider: 'B2BSlots' },
  { id: 741, name: 'Butterfly Staxx 2', provider: 'B2BSlots' },
  { id: 742, name: 'Wings of Riches', provider: 'B2BSlots' },
  { id: 743, name: 'Creature From The Black Lagoon', provider: 'B2BSlots' },
  { id: 744, name: 'The Wish Master', provider: 'B2BSlots' },
  { id: 745, name: 'The Invisible Man', provider: 'B2BSlots' },
  { id: 746, name: 'Santa Vs Rudolf', provider: 'B2BSlots' },
  { id: 747, name: 'Koi Princess', provider: 'B2BSlots' },
  { id: 748, name: 'Happy Riches', provider: 'B2BSlots' },
  { id: 749, name: 'Blackjack Classic', provider: 'B2BSlots' },
];

export const YGGDRASIL_GAME_NAMES_WITH_IDS = [
  { id: 750, name: 'Rainbow Ryan', provider: 'B2BSlots' },
  { id: 751, name: 'Penguin City', provider: 'B2BSlots' },
  { id: 752, name: 'Fruitoids', provider: 'B2BSlots' },
  { id: 753, name: 'Winter Berries', provider: 'B2BSlots' },
  { id: 754, name: 'Big Blox', provider: 'B2BSlots' },
  { id: 755, name: 'White Snake Lady', provider: 'B2BSlots' },
  { id: 756, name: 'Cazino Zeppelin', provider: 'B2BSlots' },
  { id: 757, name: 'Doubles', provider: 'B2BSlots' },
  { id: 758, name: 'Chibeasties', provider: 'B2BSlots' },
  { id: 759, name: 'Vikings Go Wild', provider: 'B2BSlots' },
  { id: 760, name: 'Bicicleta', provider: 'B2BSlots' },
  { id: 761, name: 'Valley Of The Gods', provider: 'B2BSlots' },
  { id: 762, name: 'Reptoids', provider: 'B2BSlots' },
  { id: 763, name: 'Cyrus The Virus', provider: 'B2BSlots' },
  { id: 764, name: 'Sunny Shores', provider: 'B2BSlots' },
  { id: 765, name: 'Sahara Nights', provider: 'B2BSlots' },
  { id: 766, name: 'Wilhelm Tell', provider: 'B2BSlots' },
  { id: 767, name: 'Time Travel Tigers', provider: 'B2BSlots' },
  { id: 768, name: 'The One Armed Bandit', provider: 'B2BSlots' },
  { id: 769, name: 'Incinerator', provider: 'B2BSlots' },
  { id: 770, name: 'Pumpkin Smash', provider: 'B2BSlots' },
  { id: 771, name: 'Easter Island', provider: 'B2BSlots' },
  { id: 772, name: 'Gem Rocks', provider: 'B2BSlots' },
  { id: 773, name: 'Double Dragons', provider: 'B2BSlots' },
  { id: 774, name: 'Vikings Go Berzerk', provider: 'B2BSlots' },
  { id: 775, name: 'Vikings Go To Hell', provider: 'B2BSlots' },
  { id: 776, name: 'Football Glory', provider: 'B2BSlots' },
  { id: 777, name: 'Beauty And The Beast', provider: 'B2BSlots' },
];

export const IGROSOFT_B2B_GAME_NAMES_WITH_IDS = [
  { id: 778, name: 'Keks', provider: 'B2BSlots' },
  { id: 779, name: 'Sweet Life 2', provider: 'B2BSlots' },
  { id: 780, name: 'Sweet Life', provider: 'B2BSlots' },
  { id: 781, name: 'Lucky Haunter', provider: 'B2BSlots' },
  { id: 782, name: 'Gnome', provider: 'B2BSlots' },
  { id: 783, name: 'Island 2', provider: 'B2BSlots' },
  { id: 784, name: 'Island', provider: 'B2BSlots' },
  { id: 785, name: 'Doughnut', provider: 'B2BSlots' },
  { id: 786, name: 'BetInHell', provider: 'B2BSlots' },
  { id: 787, name: 'Zombie', provider: 'B2BSlots' },
  { id: 788, name: 'Beaver builder', provider: 'B2BSlots' },
  { id: 789, name: 'Crazy monkey', provider: 'B2BSlots' },
  { id: 790, name: 'Paperman', provider: 'B2BSlots' },
  { id: 791, name: 'Resident', provider: 'B2BSlots' },
  { id: 792, name: 'Fruit Coctail', provider: 'B2BSlots' },
  { id: 793, name: 'Fruit Salad', provider: 'B2BSlots' },
  { id: 794, name: 'Garage', provider: 'B2BSlots' },
  { id: 795, name: 'Crazy Monkey 2', provider: 'B2BSlots' },
];

export const NOVOMATIC_DELUXE_GAME_NAMES_WITH_IDS = [
  { id: 796, name: 'Fruits and royals', provider: 'B2BSlots' },
  { id: 797, name: 'Diamond 7', provider: 'B2BSlots' },
  { id: 798, name: 'Hot cubes', provider: 'B2BSlots' },
  { id: 799, name: 'Inferno', provider: 'B2BSlots' },
  { id: 800, name: 'Sizzling gems', provider: 'B2BSlots' },
  { id: 801, name: 'Fruit sensation', provider: 'B2BSlots' },
  { id: 802, name: 'Fruitilicious', provider: 'B2BSlots' },
  { id: 803, name: 'Mystery star', provider: 'B2BSlots' },
  { id: 804, name: 'Dazzling diamonds', provider: 'B2BSlots' },
  { id: 805, name: 'Mafia', provider: 'B2BSlots' },
  { id: 806, name: 'Glittering peaks', provider: 'B2BSlots' },
  { id: 807, name: 'Cosmic miracle', provider: 'B2BSlots' },
  { id: 808, name: 'Knightly valor', provider: 'B2BSlots' },
  { id: 809, name: 'Book of ra classic', provider: 'B2BSlots' },
  { id: 810, name: 'Golden ark', provider: 'B2BSlots' },
  { id: 811, name: 'Red lady', provider: 'B2BSlots' },
  { id: 812, name: 'Faust', provider: 'B2BSlots' },
  { id: 813, name: 'Lord of ocean', provider: 'B2BSlots' },
  { id: 814, name: 'Columbus deluxe', provider: 'B2BSlots' },
  { id: 815, name: 'Money game deluxe', provider: 'B2BSlots' },
  { id: 816, name: 'Alchemist', provider: 'B2BSlots' },
  { id: 817, name: 'Angry birds', provider: 'B2BSlots' },
  { id: 818, name: 'Magic Princess', provider: 'B2BSlots' },
  { id: 819, name: 'Cryptic highway', provider: 'B2BSlots' },
  { id: 820, name: 'Caribbean Holidays', provider: 'B2BSlots' },
  { id: 821, name: 'Columbus', provider: 'B2BSlots' },
  { id: 822, name: 'Bananas Go Bahamas', provider: 'B2BSlots' },
  { id: 823, name: 'Bee Bop', provider: 'B2BSlots' },
  { id: 824, name: 'Beetle Mania', provider: 'B2BSlots' },
  { id: 825, name: 'Banana Splash', provider: 'B2BSlots' },
  { id: 826, name: 'Atilla', provider: 'B2BSlots' },
  { id: 827, name: 'Dynasty Of Ming', provider: 'B2BSlots' },
  { id: 828, name: 'Emperrors China', provider: 'B2BSlots' },
  { id: 829, name: 'Gold Craze', provider: 'B2BSlots' },
  { id: 830, name: 'Egyptian Experience', provider: 'B2BSlots' },
  { id: 831, name: 'Beetle Mania Deluxe', provider: 'B2BSlots' },
  { id: 832, name: 'Gryphons Gold', provider: 'B2BSlots' },
  { id: 833, name: 'Hanniball Of Charthago', provider: 'B2BSlots' },
  { id: 834, name: 'Money Game', provider: 'B2BSlots' },
  { id: 835, name: 'Pharaohs Gold II Deluxe', provider: 'B2BSlots' },
  { id: 836, name: 'Pharaohs Gold III', provider: 'B2BSlots' },
  { id: 837, name: 'Polar Fox', provider: 'B2BSlots' },
  { id: 838, name: 'Royal Treasures', provider: 'B2BSlots' },
  { id: 839, name: 'Secret Forest', provider: 'B2BSlots' },
  { id: 840, name: 'Silver Fox', provider: 'B2BSlots' },
  { id: 841, name: 'The Ming Dynasty', provider: 'B2BSlots' },
  { id: 842, name: 'Unicorn Magic', provider: 'B2BSlots' },
  { id: 843, name: 'Wonderful Fluite', provider: 'B2BSlots' },
  { id: 844, name: 'Sizzling Hot', provider: 'B2BSlots' },
  { id: 845, name: 'Just jewels', provider: 'B2BSlots' },
  { id: 846, name: 'Moorhuhn', provider: 'B2BSlots' },
  { id: 847, name: 'Lucky Lady', provider: 'B2BSlots' },
  { id: 848, name: 'Mario', provider: 'B2BSlots' },
  { id: 849, name: 'Hot Target', provider: 'B2BSlots' },
  { id: 850, name: 'Hot Volee', provider: 'B2BSlots' },
  { id: 851, name: 'Fruit farm', provider: 'B2BSlots' },
  { id: 852, name: 'Cold Spell', provider: 'B2BSlots' },
  { id: 853, name: 'Always Hot Cubes', provider: 'B2BSlots' },
  { id: 854, name: 'Always Hot Deluxe', provider: 'B2BSlots' },
  { id: 855, name: 'Always Hot', provider: 'B2BSlots' },
  { id: 856, name: 'Always Wet', provider: 'B2BSlots' },
  { id: 857, name: 'Ultra Hot Deluxe', provider: 'B2BSlots' },
  { id: 858, name: 'Ultra Hot', provider: 'B2BSlots' },
  { id: 859, name: 'Ultra Gems', provider: 'B2BSlots' },
  { id: 860, name: 'Sizzling Crowns', provider: 'B2BSlots' },
  { id: 861, name: 'Just Fruits', provider: 'B2BSlots' },
  { id: 862, name: 'Holmes & Watson Deluxe', provider: 'B2BSlots' },
  { id: 863, name: 'Golden Prophecies Deluxe', provider: 'B2BSlots' },
  { id: 864, name: 'Gate Of Ra Deluxe', provider: 'B2BSlots' },
  { id: 865, name: 'Always American', provider: 'B2BSlots' },
  { id: 866, name: 'All American', provider: 'B2BSlots' },
  { id: 867, name: 'Age Of Heroes Deluxe', provider: 'B2BSlots' },
  { id: 868, name: 'Book Of Moorhuhn', provider: 'B2BSlots' },
  { id: 869, name: 'Helena', provider: 'B2BSlots' },
  { id: 870, name: 'Reel King', provider: 'B2BSlots' },
  { id: 871, name: 'Sharky', provider: 'B2BSlots' },
  { id: 872, name: 'Book Of Ra HD', provider: 'B2BSlots' },
  { id: 873, name: "Santa's Riches", provider: 'B2BSlots' },
  { id: 874, name: 'Dolphins pearl deluxe', provider: 'B2BSlots' },
  { id: 875, name: 'Book of ra deluxe', provider: 'B2BSlots' },
  { id: 876, name: 'Gryphons gold deluxe', provider: 'B2BSlots' },
  { id: 877, name: 'Dolphins pearl classic', provider: 'B2BSlots' },
  { id: 878, name: "Lucky lady's charm deluxe", provider: 'B2BSlots' },
  { id: 879, name: 'Sea sirens', provider: 'B2BSlots' },
  { id: 880, name: 'Sizzling hot deluxe', provider: 'B2BSlots' },
  { id: 881, name: 'Kings of cards', provider: 'B2BSlots' },
  { id: 882, name: 'Just jewels deluxe', provider: 'B2BSlots' },
];

export const BET_IN_HELL_GAME_NAMES_WITH_IDS = [
  { id: 883, name: 'Book Of Sunrise', provider: 'B2BSlots' },
  { id: 884, name: 'Book Of Dark Sun', provider: 'B2BSlots' },
  { id: 885, name: 'Book Of Sahara', provider: 'B2BSlots' },
  { id: 886, name: 'Joker Strike Again', provider: 'B2BSlots' },
  { id: 887, name: 'Forest ant', provider: 'B2BSlots' },
  { id: 888, name: 'Maniac house', provider: 'B2BSlots' },
  { id: 889, name: 'Sea underwater club', provider: 'B2BSlots' },
  { id: 890, name: 'Revenge of cyborgs', provider: 'B2BSlots' },
  { id: 891, name: 'Evil Genotype', provider: 'B2BSlots' },
  { id: 892, name: 'Sweet paradise', provider: 'B2BSlots' },
  { id: 893, name: 'Space Battle', provider: 'B2BSlots' },
  { id: 894, name: 'Cheerful farmer', provider: 'B2BSlots' },
  { id: 895, name: 'Gemstone Of Aztec', provider: 'B2BSlots' },
  { id: 896, name: 'Lapland', provider: 'B2BSlots' },
  { id: 897, name: 'Treasure of shaman', provider: 'B2BSlots' },
  { id: 898, name: 'Don Slottione', provider: 'B2BSlots' },
  { id: 899, name: 'Goblins Land', provider: 'B2BSlots' },
  { id: 900, name: 'Horror Castle', provider: 'B2BSlots' },
  { id: 901, name: 'Deep Blue Sea', provider: 'B2BSlots' },
  { id: 902, name: 'Super Hamster', provider: 'B2BSlots' },
  { id: 903, name: 'Frozen Rich Joker', provider: 'B2BSlots' },
  { id: 904, name: 'Joker Win Spin', provider: 'B2BSlots' },
  { id: 905, name: 'Romance V', provider: 'B2BSlots' },
  { id: 906, name: 'The Sword & The Magic', provider: 'B2BSlots' },
  { id: 907, name: 'Divine Carnival', provider: 'B2BSlots' },
  { id: 908, name: "Cleopatra's Diary", provider: 'B2BSlots' },
  { id: 909, name: 'Imhotep Manuscript', provider: 'B2BSlots' },
  { id: 910, name: 'Resident 3D', provider: 'B2BSlots' },
  { id: 911, name: "Warlock's Book", provider: 'B2BSlots' },
  { id: 912, name: 'Wild Rodeo', provider: 'B2BSlots' },
  { id: 913, name: 'Brave Mongoose', provider: 'B2BSlots' },
  { id: 914, name: 'Gates of Hell', provider: 'B2BSlots' },
  { id: 915, name: 'Spin Joker Spin', provider: 'B2BSlots' },
];

export const BELATRA_GAME_NAMES_WITH_IDS = [
  { id: 916, name: 'Fairy Land 2', provider: 'B2BSlots' },
  { id: 917, name: 'Lucky Drink', provider: 'B2BSlots' },
  { id: 918, name: 'Chukcha', provider: 'B2BSlots' },
  { id: 919, name: 'Alcatraz', provider: 'B2BSlots' },
];

export const UNICUM_GAME_NAMES_WITH_IDS = [
  { id: 920, name: 'Bratva', provider: 'B2BSlots' },
  { id: 921, name: 'Zoloto Partii', provider: 'B2BSlots' },
  { id: 922, name: 'Bazar', provider: 'B2BSlots' },
  { id: 923, name: 'Robinson', provider: 'B2BSlots' },
  { id: 924, name: 'Around The World', provider: 'B2BSlots' },
];

export const MEGAJACK_B2B_GAME_NAMES_WITH_IDS = [
  { id: 925, name: 'Slot-o-pol Deluxe', provider: 'B2BSlots' },
  { id: 926, name: 'Slot-o-pol', provider: 'B2BSlots' },
  { id: 927, name: 'Aztec Gold', provider: 'B2BSlots' },
  { id: 928, name: 'Champagne', provider: 'B2BSlots' },
];

export const PLAYTECH_GAME_NAMES_WITH_IDS = [
  { id: 929, name: 'Azteca', provider: 'B2BSlots' },
  { id: 930, name: 'Le Comte de Monte Cristo', provider: 'B2BSlots' },
  { id: 931, name: 'New space adventure', provider: 'B2BSlots' },
  { id: 932, name: "Captain's Treasure Pro", provider: 'B2BSlots' },
  { id: 933, name: 'New Year Girls', provider: 'B2BSlots' },
  { id: 934, name: 'Nights', provider: 'B2BSlots' },
  { id: 935, name: 'Pirates Slots', provider: 'B2BSlots' },
  { id: 936, name: 'Rockabilly', provider: 'B2BSlots' },
  { id: 937, name: 'Viking Striking', provider: 'B2BSlots' },
  { id: 938, name: 'World Travel', provider: 'B2BSlots' },
  { id: 939, name: 'Riddle Jungle', provider: 'B2BSlots' },
  { id: 940, name: 'Cute And Fluffy', provider: 'B2BSlots' },
  { id: 941, name: 'Rome & Glory', provider: 'B2BSlots' },
  { id: 942, name: 'Thai Paradise', provider: 'B2BSlots' },
];

export const PLAY_N_GO_GAME_NAMES_WITH_IDS = [
  { id: 943, name: 'Doom Of Dead', provider: 'B2BSlots' },
  { id: 944, name: 'JewelBox', provider: 'B2BSlots' },
  { id: 945, name: 'Lady Of Fortune', provider: 'B2BSlots' },
  { id: 946, name: 'Samba Carnival', provider: 'B2BSlots' },
  { id: 947, name: 'Merry Xmas', provider: 'B2BSlots' },
  { id: 948, name: 'Book Of Dead', provider: 'B2BSlots' },
  { id: 949, name: 'Doom Of Egypt', provider: 'B2BSlots' },
  { id: 950, name: 'Photo Safari', provider: 'B2BSlots' },
  { id: 951, name: 'Aztec Warrior Princess', provider: 'B2BSlots' },
  { id: 952, name: 'Fortune Teller', provider: 'B2BSlots' },
  { id: 953, name: 'Space Race', provider: 'B2BSlots' },
  { id: 954, name: 'Sails Of Gold', provider: 'B2BSlots' },
  { id: 955, name: 'Prosperity Palace', provider: 'B2BSlots' },
  { id: 956, name: 'Star Joker', provider: 'B2BSlots' },
  { id: 957, name: 'Happy Halloween', provider: 'B2BSlots' },
  { id: 958, name: 'Golden Legend', provider: 'B2BSlots' },
  { id: 959, name: 'Xmas Magic', provider: 'B2BSlots' },
  { id: 960, name: 'Holiday Season', provider: 'B2BSlots' },
  { id: 961, name: 'Royal Masquerade', provider: 'B2BSlots' },
  { id: 962, name: 'Pimped', provider: 'B2BSlots' },
  { id: 963, name: 'Reactoonz', provider: 'B2BSlots' },
  { id: 964, name: 'Aztec Idols', provider: 'B2BSlots' },
  { id: 965, name: 'Chinese New Year', provider: 'B2BSlots' },
  { id: 966, name: 'Ninja Fruits', provider: 'B2BSlots' },
  { id: 967, name: 'Fire Joker', provider: 'B2BSlots' },
  { id: 968, name: 'Scroll Of Dead', provider: 'B2BSlots' },
  { id: 969, name: 'Amulet Of Dead', provider: 'B2BSlots' },
  { id: 970, name: 'Pearl Lagoon', provider: 'B2BSlots' },
  { id: 971, name: 'Myth', provider: 'B2BSlots' },
  { id: 972, name: 'Gold Trophy 2', provider: 'B2BSlots' },
  { id: 973, name: 'Inferno Star', provider: 'B2BSlots' },
  { id: 974, name: 'Inferno Joker', provider: 'B2BSlots' },
  { id: 975, name: 'Big Win Cat', provider: 'B2BSlots' },
  { id: 976, name: 'Rise Of Dead', provider: 'B2BSlots' },
  { id: 977, name: 'Gold King', provider: 'B2BSlots' },
  { id: 978, name: 'Dawn Of Egypt', provider: 'B2BSlots' },
  { id: 979, name: 'Eclipse of the Sun God', provider: 'B2BSlots' },
  { id: 980, name: 'Ankh Of Anubis', provider: 'B2BSlots' },
  { id: 981, name: 'Legacy Of Egypt', provider: 'B2BSlots' },
  { id: 982, name: 'Merlin And Morgana', provider: 'B2BSlots' },
  { id: 983, name: 'Fu Er Dai', provider: 'B2BSlots' },
  { id: 984, name: 'Spin Party', provider: 'B2BSlots' },
  { id: 985, name: 'Secret Of Dead', provider: 'B2BSlots' },
  { id: 986, name: 'Lost Chapter', provider: 'B2BSlots' },
  { id: 987, name: "King's Mask", provider: 'B2BSlots' },
  { id: 988, name: 'Eye Of Atum', provider: 'B2BSlots' },
  { id: 989, name: 'Pyramids of Dead', provider: 'B2BSlots' },
  { id: 990, name: 'Wandering City', provider: 'B2BSlots' },
  { id: 991, name: 'Sticky Joker', provider: 'B2BSlots' },
  { id: 992, name: 'Mystery Joker', provider: 'B2BSlots' },
  { id: 993, name: 'Xmas Joker', provider: 'B2BSlots' },
  { id: 994, name: 'Naughty Nicks Book', provider: 'B2BSlots' },
  { id: 995, name: 'Riches Of Ra', provider: 'B2BSlots' },
  { id: 996, name: 'Dragon Ship', provider: 'B2BSlots' },
  { id: 997, name: 'Pilgrim Of Dead', provider: 'B2BSlots' },
  { id: 998, name: 'Legacy Of Inca', provider: 'B2BSlots' },
  { id: 999, name: 'Blazin Bullfrog', provider: 'B2BSlots' },
  { id: 1000, name: 'Crystal Sun', provider: 'B2BSlots' },
  { id: 1001, name: 'Athena Ascending', provider: 'B2BSlots' },
  { id: 1002, name: 'Rise Of Athena', provider: 'B2BSlots' },
  { id: 1003, name: 'Love Joker', provider: 'B2BSlots' },
  { id: 1004, name: 'Shield Of Athena', provider: 'B2BSlots' },
  { id: 1005, name: 'Immor Tails', provider: 'B2BSlots' },
  { id: 1006, name: "That's Rich", provider: 'B2BSlots' },
  { id: 1007, name: 'Rascal Riches', provider: 'B2BSlots' },
  { id: 1008, name: 'Count Jokula', provider: 'B2BSlots' },
  { id: 1009, name: 'Gates Of Troy', provider: 'B2BSlots' },
  { id: 1010, name: 'the Sword and the Grail', provider: 'B2BSlots' },
  { id: 1011, name: 'Ice Joker', provider: 'B2BSlots' },
  { id: 1012, name: 'the Green Knight', provider: 'B2BSlots' },
  { id: 1013, name: '15 Crystal Roses', provider: 'B2BSlots' },
  { id: 1014, name: 'Diamonds of the Realm', provider: 'B2BSlots' },
  { id: 1015, name: 'Cash a Cabana', provider: 'B2BSlots' },
  { id: 1016, name: 'Blinged', provider: 'B2BSlots' },
  { id: 1017, name: 'New Year Riches', provider: 'B2BSlots' },
  { id: 1018, name: 'Rise Of Gods:Reckoning', provider: 'B2BSlots' },
  { id: 1019, name: "Freya's Wedding", provider: 'B2BSlots' },
  { id: 1020, name: 'Scroll Of Seth', provider: 'B2BSlots' },
  { id: 1021, name: "Merlin's Grimoire", provider: 'B2BSlots' },
  { id: 1022, name: 'The Wild Class', provider: 'B2BSlots' },
  { id: 1023, name: 'Tale Of Kyubiko', provider: 'B2BSlots' },
  { id: 1024, name: 'Canine Carnage', provider: 'B2BSlots' },
  { id: 1025, name: 'Fox Mayhem', provider: 'B2BSlots' },
  { id: 1026, name: 'Legion Gold', provider: 'B2BSlots' },
  { id: 1027, name: 'Rocco Gallo', provider: 'B2BSlots' },
  { id: 1028, name: 'Mega Don', provider: 'B2BSlots' },
  { id: 1029, name: 'Fire Toad', provider: 'B2BSlots' },
  { id: 1030, name: 'Boat Bonanza', provider: 'B2BSlots' },
  { id: 1031, name: 'Mount M', provider: 'B2BSlots' },
  { id: 1032, name: 'Tome of Madness', provider: 'B2BSlots' },
  { id: 1033, name: 'Rise Of Merlin', provider: 'B2BSlots' },
  { id: 1034, name: 'Legacy Of Dead', provider: 'B2BSlots' },
];

export const EROTIC_B2B_GAME_NAMES_WITH_IDS = [
  { id: 1035, name: 'Erotic Fantasy', provider: 'B2BSlots' },
  { id: 1036, name: 'Suicide Squad', provider: 'B2BSlots' },
  { id: 1037, name: 'Star Wars', provider: 'B2BSlots' },
  { id: 1038, name: 'Secret Of Temptation', provider: 'B2BSlots' },
  { id: 1039, name: 'Secret Of Seduction', provider: 'B2BSlots' },
  { id: 1040, name: 'Queen Of Thrones', provider: 'B2BSlots' },
  { id: 1041, name: 'Kill Bill', provider: 'B2BSlots' },
  { id: 1042, name: 'Ghost Busters', provider: 'B2BSlots' },
  { id: 1043, name: 'Chica Boom', provider: 'B2BSlots' },
  { id: 1044, name: 'Captain America', provider: 'B2BSlots' },
  { id: 1045, name: 'Avengers', provider: 'B2BSlots' },
  { id: 1046, name: 'Avatar', provider: 'B2BSlots' },
];

export const MICROGAMING_B2B_GAME_NAMES_WITH_IDS = [
  { id: 1047, name: 'Game Of Thrones', provider: 'B2BSlots' },
  { id: 1048, name: 'Matrix Resurrections', provider: 'B2BSlots' },
];

export const PRAGMATIC_PLAY_GAME_NAMES_WITH_IDS = [
  { id: 1049, name: 'Book Of Tut', provider: 'B2BSlots' },
  { id: 1050, name: 'Book of Vikings', provider: 'B2BSlots' },
  { id: 1051, name: 'Return of the Dead', provider: 'B2BSlots' },
  { id: 1052, name: 'Scarab Queen', provider: 'B2BSlots' },
  { id: 1053, name: 'Heart of Rio', provider: 'B2BSlots' },
  { id: 1054, name: 'Madame Destiny', provider: 'B2BSlots' },
  { id: 1055, name: 'Ancient Egypt Classic', provider: 'B2BSlots' },
  { id: 1056, name: 'Ancient Egypt', provider: 'B2BSlots' },
  { id: 1057, name: 'Super 7s', provider: 'B2BSlots' },
  { id: 1058, name: "Joker's Jewels", provider: 'B2BSlots' },
  { id: 1059, name: 'Fruit Rainbow', provider: 'B2BSlots' },
  { id: 1060, name: 'Mysterious Egypt', provider: 'B2BSlots' },
  { id: 1061, name: 'Triple Jokers', provider: 'B2BSlots' },
  { id: 1062, name: 'Triple Dragons', provider: 'B2BSlots' },
  { id: 1063, name: 'Super Joker', provider: 'B2BSlots' },
  { id: 1064, name: 'The Catfather', provider: 'B2BSlots' },
  { id: 1065, name: 'Hockey League Wild Match', provider: 'B2BSlots' },
  { id: 1066, name: 'Hercules Son of Zeus', provider: 'B2BSlots' },
  { id: 1067, name: 'Lucky Dragons', provider: 'B2BSlots' },
  { id: 1068, name: 'Hot To Burn', provider: 'B2BSlots' },
  { id: 1069, name: 'Aztec Gems', provider: 'B2BSlots' },
  { id: 1070, name: 'Master Joker', provider: 'B2BSlots' },
  { id: 1071, name: '888 Dragons', provider: 'B2BSlots' },
  { id: 1072, name: 'Triple Tigers', provider: 'B2BSlots' },
  { id: 1073, name: 'Treasure Horse', provider: 'B2BSlots' },
  { id: 1074, name: 'Book of the Fallen', provider: 'B2BSlots' },
  { id: 1075, name: 'Hot Safari', provider: 'B2BSlots' },
  { id: 1076, name: 'Wild Gladiators', provider: 'B2BSlots' },
  { id: 1077, name: 'The Dog House', provider: 'B2BSlots' },
  { id: 1078, name: 'Sweet Bonanza', provider: 'B2BSlots' },
  { id: 1079, name: 'Sweet Bonanza Xmas', provider: 'B2BSlots' },
  { id: 1080, name: 'Gates Of Olympus', provider: 'B2BSlots' },
  { id: 1081, name: 'Starlight Princess', provider: 'B2BSlots' },
  { id: 1119, name: 'Golden Ox', provider: 'B2BSlots' },
  { id: 1082, name: 'Gates of Aztec', provider: 'B2BSlots' },
  { id: 1083, name: 'Gates of Hades', provider: 'B2BSlots' },
  { id: 1084, name: 'Gates of Gatot Kaca', provider: 'B2BSlots' },
  { id: 1085, name: 'Starlight Christmas', provider: 'B2BSlots' },
  { id: 1086, name: 'Hockey Bonanza', provider: 'B2BSlots' },
  { id: 1087, name: 'Sweet Bonanza Dice', provider: 'B2BSlots' },
  { id: 1088, name: 'Pyramid Bonanza', provider: 'B2BSlots' },
  { id: 1089, name: 'the Dog House Dice Show', provider: 'B2BSlots' },
  { id: 1090, name: 'Fortune of Giza', provider: 'B2BSlots' },
  { id: 1091, name: 'Jokers Jewels Dice', provider: 'B2BSlots' },
  { id: 1092, name: 'The Tweety House', provider: 'B2BSlots' },
  { id: 1093, name: 'Book of Aztec King', provider: 'B2BSlots' },
  { id: 1094, name: 'Juicy Fruits', provider: 'B2BSlots' },
  { id: 1095, name: 'Big Bass Bonanza', provider: 'B2BSlots' },
  { id: 1096, name: 'Christmas Big Bass Bonanza', provider: 'B2BSlots' },
  { id: 1097, name: 'Extra Juicy', provider: 'B2BSlots' },
  { id: 1098, name: 'Fire Strike', provider: 'B2BSlots' },
  { id: 1099, name: 'Fire Strike 2', provider: 'B2BSlots' },
  { id: 1100, name: 'Wild West Gold', provider: 'B2BSlots' },
  { id: 1101, name: 'Rise of Samurai III', provider: 'B2BSlots' },
  { id: 1102, name: 'Joker King', provider: 'B2BSlots' },
  { id: 1103, name: 'Wild Wild Riches', provider: 'B2BSlots' },
  { id: 1104, name: 'The Hand of Midas', provider: 'B2BSlots' },
  { id: 1105, name: 'Bigger Bass Bonanza', provider: 'B2BSlots' },
  { id: 1106, name: 'Big Bass Keeping it Reel', provider: 'B2BSlots' },
  { id: 1107, name: 'Sugar Rush', provider: 'B2BSlots' },
  { id: 1108, name: 'Sugar Twist', provider: 'B2BSlots' },
  { id: 1109, name: 'Mochimon', provider: 'B2BSlots' },
  { id: 1110, name: 'Guarana eyes of the Amazon', provider: 'B2BSlots' },
  { id: 1111, name: 'Fruit Party 2', provider: 'B2BSlots' },
  { id: 1112, name: 'Wild Beach Party', provider: 'B2BSlots' },
  { id: 1113, name: 'Fruit Party', provider: 'B2BSlots' },
  { id: 1114, name: 'Cleocatra', provider: 'B2BSlots' },
  { id: 1115, name: 'Wolf Gold', provider: 'B2BSlots' },
  { id: 1116, name: 'Lucky New Year Tiger Treasures', provider: 'B2BSlots' },
  { id: 1117, name: 'Lucky New Year', provider: 'B2BSlots' },
  { id: 1118, name: 'Money Mouse', provider: 'B2BSlots' },
  { id: 1120, name: 'Bull Fiesta', provider: 'B2BSlots' },
  { id: 1121, name: 'Madame Destiny Megaways', provider: 'B2BSlots' },
  { id: 1122, name: 'Old Gold Miner Megaways', provider: 'B2BSlots' },
  { id: 1123, name: 'Sword of Ares', provider: 'B2BSlots' },
  { id: 1124, name: 'Joker Blast Bonanza', provider: 'B2BSlots' },
  { id: 1125, name: 'Wild Hop&Drop', provider: 'B2BSlots' },
  { id: 1126, name: 'LadyBug Luck', provider: 'B2BSlots' },
  { id: 1127, name: 'Santas Wonderland', provider: 'B2BSlots' },
  { id: 1128, name: 'Gems Bonanza', provider: 'B2BSlots' },
  { id: 1129, name: 'Big Bass Bonanza Megaways', provider: 'B2BSlots' },
  { id: 1130, name: 'Gemstone', provider: 'B2BSlots' },
  { id: 1131, name: 'Tucanito', provider: 'B2BSlots' },
  { id: 1132, name: 'Yi Sun Shin', provider: 'B2BSlots' },
  { id: 1133, name: 'John Hunter Nellantica Roma', provider: 'B2BSlots' },
  { id: 1134, name: 'Gemine', provider: 'B2BSlots' },
  { id: 1135, name: 'Big Juan', provider: 'B2BSlots' },
  { id: 1136, name: 'Mr Toad Gold Megaways', provider: 'B2BSlots' },
  { id: 1137, name: 'The Dog House Megaways', provider: 'B2BSlots' },
  { id: 1138, name: 'Bigger Bass Blizzard Christmas Catch', provider: 'B2BSlots' },
  { id: 1139, name: 'Sugar Rush Xmas', provider: 'B2BSlots' },
  { id: 1140, name: 'Club Tropicana', provider: 'B2BSlots' },
  { id: 1141, name: 'Buffalo King Megaways', provider: 'B2BSlots' },
  { id: 1142, name: 'Big Bass Splash', provider: 'B2BSlots' },
  { id: 1143, name: 'Book of Tut Megaways', provider: 'B2BSlots' },
  { id: 1144, name: 'Hot Fiesta', provider: 'B2BSlots' },
  { id: 1145, name: 'Might of Ra', provider: 'B2BSlots' },
  { id: 1146, name: 'Great Rhino', provider: 'B2BSlots' },
  { id: 1147, name: 'Great Rhino Deluxe', provider: 'B2BSlots' },
  { id: 1148, name: 'Forge of Olympus', provider: 'B2BSlots' },
  { id: 1149, name: 'Gates of Xibalba', provider: 'B2BSlots' },
  { id: 1150, name: 'Santas Great Gifts', provider: 'B2BSlots' },
  { id: 1151, name: 'Candy Blitz', provider: 'B2BSlots' },
  { id: 1152, name: 'Xmas Spark', provider: 'B2BSlots' },
  { id: 1153, name: 'Cyber Heist', provider: 'B2BSlots' },
  { id: 1154, name: 'Wisdom of Athena', provider: 'B2BSlots' },
  { id: 1155, name: 'Gates of Olympus 1000', provider: 'B2BSlots' },
  { id: 1156, name: 'Starlight Princess 1000', provider: 'B2BSlots' },
  { id: 1157, name: 'Jewel Rush', provider: 'B2BSlots' },
  { id: 1158, name: 'Cash Patrol', provider: 'B2BSlots' },
  { id: 1159, name: 'Great Rhino Megaways', provider: 'B2BSlots' },
  { id: 1160, name: 'Christmas Carol Megaways', provider: 'B2BSlots' },
  { id: 1161, name: 'Mr Tains Fishing Adventures', provider: 'B2BSlots' },
  { id: 1162, name: 'Saray Ruyasi', provider: 'B2BSlots' },
  { id: 1163, name: 'Sasuntsi Davit', provider: 'B2BSlots' },
  { id: 1164, name: 'Supermania', provider: 'B2BSlots' },
  { id: 1165, name: 'Saiyan Mania', provider: 'B2BSlots' },
  { id: 1166, name: 'Buffalo King', provider: 'B2BSlots' },
  { id: 1167, name: 'Bison Spirit', provider: 'B2BSlots' },
  { id: 1168, name: 'Magicians Secrets', provider: 'B2BSlots' },
  { id: 1169, name: 'Robber Strike', provider: 'B2BSlots' },
  { id: 1170, name: 'Wildman Super Bonanza', provider: 'B2BSlots' },
  { id: 1171, name: 'Aztec King Megaways', provider: 'B2BSlots' },
  { id: 1172, name: 'Rise of Samurai Megaways', provider: 'B2BSlots' },
  { id: 1173, name: 'Gates of Heaven', provider: 'B2BSlots' },
  { id: 1174, name: 'Happy Fortune', provider: 'B2BSlots' },
  { id: 1175, name: 'Gates of Olympus Dice', provider: 'B2BSlots' },
  { id: 1176, name: 'Aztec King', provider: 'B2BSlots' },
  { id: 1177, name: 'Holiday Ride', provider: 'B2BSlots' },
  { id: 1178, name: 'The Tiger Warrior', provider: 'B2BSlots' },
  { id: 1179, name: 'Lucky Dragon Ball', provider: 'B2BSlots' },
  { id: 1180, name: 'Gold Party', provider: 'B2BSlots' },
  { id: 1181, name: 'Gorilla Mayhem', provider: 'B2BSlots' },
  { id: 1182, name: 'Moonshot', provider: 'B2BSlots' },
  { id: 1183, name: 'Clover Gold', provider: 'B2BSlots' },
  { id: 1184, name: 'Kingdom of Asgard', provider: 'B2BSlots' },
  { id: 1185, name: 'Power of Ninja', provider: 'B2BSlots' },
  { id: 1186, name: 'Bali Dragon', provider: 'B2BSlots' },
  { id: 1187, name: 'Jeitinho Brasileiro', provider: 'B2BSlots' },
  { id: 1188, name: 'HokkaidoWolf', provider: 'B2BSlots' },
  { id: 1189, name: 'Golden Pig', provider: 'B2BSlots' },
  { id: 1190, name: 'Little Gem', provider: 'B2BSlots' },
  { id: 1191, name: 'Ultra Hold and Spin', provider: 'B2BSlots' },
  { id: 1192, name: 'Animal Magic 1000', provider: 'B2BSlots' },
  { id: 1193, name: '5 Lions Megaways', provider: 'B2BSlots' },
  { id: 1194, name: '5 Frozen Charms Megaways', provider: 'B2BSlots' },
  { id: 1195, name: '5 Rabbits Megaways', provider: 'B2BSlots' },
  { id: 1196, name: 'Lucky Phoenix Megaways', provider: 'B2BSlots' },
  { id: 1197, name: 'Casino Heist Megaways', provider: 'B2BSlots' },
  { id: 1198, name: 'Big Bass Halloween', provider: 'B2BSlots' },
  { id: 1199, name: 'Big Bass Christmas Bash', provider: 'B2BSlots' },
  { id: 1200, name: 'Big Bass Amazon Xtreme', provider: 'B2BSlots' },
  { id: 1201, name: 'Big Bass Day at the Races', provider: 'B2BSlots' },
  { id: 1202, name: 'The Dog House - Dog or Alive', provider: 'B2BSlots' },
  { id: 1203, name: 'The Dog House Multihold', provider: 'B2BSlots' },
  { id: 1204, name: 'Sugar Rush 1000', provider: 'B2BSlots' },
  { id: 1205, name: 'Octobeer Fortunes', provider: 'B2BSlots' },
  { id: 1206, name: 'Treasure Wild', provider: 'B2BSlots' },
  { id: 1207, name: 'Zeus vs Hades - Gods of War', provider: 'B2BSlots' },
  { id: 1208, name: 'Rise of Samurai IV', provider: 'B2BSlots' },
  { id: 1209, name: 'Train to Seoul', provider: 'B2BSlots' },
  { id: 1210, name: 'Sweet Bonanza 1000', provider: 'B2BSlots' },
  { id: 1211, name: 'Treasure Trawler', provider: 'B2BSlots' },
  { id: 1212, name: 'Rise of Montezuma', provider: 'B2BSlots' },
  { id: 1213, name: 'Monkey King Rush', provider: 'B2BSlots' },
  { id: 1214, name: 'Wild Wild Gladiator', provider: 'B2BSlots' },
  { id: 1215, name: 'The Conqueror', provider: 'B2BSlots' },
  { id: 1216, name: 'Hand of Midas 2', provider: 'B2BSlots' },
  { id: 1217, name: 'Games in Olympus', provider: 'B2BSlots' },
  { id: 1218, name: 'Samurai Code', provider: 'B2BSlots' },
  { id: 1219, name: 'Puffers vs Sharks', provider: 'B2BSlots' },
  { id: 1220, name: 'To Peiratiko Multihold', provider: 'B2BSlots' },
  { id: 1221, name: 'The Green Sun', provider: 'B2BSlots' },
  { id: 1222, name: 'Sugar Rush Dice', provider: 'B2BSlots' },
  { id: 1223, name: 'Wolf Gold Dice', provider: 'B2BSlots' },
  { id: 1224, name: 'Cyber Heist 1000', provider: 'B2BSlots' },
  { id: 1225, name: 'Dragon Gold 88', provider: 'B2BSlots' },
  { id: 1226, name: 'Trolling 1000', provider: 'B2BSlots' },
  { id: 1227, name: 'Mafiosa Dead or a Llama', provider: 'B2BSlots' },
  { id: 1228, name: 'Gold Carp Bonanza', provider: 'B2BSlots' },
  { id: 1229, name: 'Big Bass Halloween 2', provider: 'B2BSlots' },
  { id: 1230, name: 'Wild Wild Rage', provider: 'B2BSlots' },
  { id: 1231, name: 'Barbar', provider: 'B2BSlots' },
];

export const PUSH_GAMING_GAME_NAMES_WITH_IDS = [
  { id: 1240, name: 'Deadly 5', provider: 'B2BSlots' },
  { id: 1239, name: 'Jammin Jars', provider: 'B2BSlots' },
  { id: 1232, name: 'Hearts Highway', provider: 'B2BSlots' },
  { id: 1233, name: 'Fat Santa', provider: 'B2BSlots' },
  { id: 1234, name: 'Fat Rabbit', provider: 'B2BSlots' },
  { id: 1235, name: '10 Swords', provider: 'B2BSlots' },
  { id: 1236, name: 'Fire Hopper', provider: 'B2BSlots' },
  { id: 1237, name: 'Razor Shark', provider: 'B2BSlots' },
  { id: 1238, name: 'Blaze Of Ra', provider: 'B2BSlots' },
  { id: 1241, name: 'Retro Tapes', provider: 'B2BSlots' },
  { id: 1242, name: 'Fat Banker', provider: 'B2BSlots' },
  { id: 1243, name: 'Bison Battle', provider: 'B2BSlots' },
  { id: 1244, name: 'Crystal Catcher', provider: 'B2BSlots' },
  { id: 1245, name: 'Giga Jar', provider: 'B2BSlots' },
  { id: 1246, name: 'Joker Troupe', provider: 'B2BSlots' },
  { id: 1247, name: "Fish 'n' Nudge", provider: 'B2BSlots' },
  { id: 1248, name: 'Mystery Mission To The Moon', provider: 'B2BSlots' },
  { id: 1249, name: 'TikiTumble', provider: 'B2BSlots' },
  { id: 1250, name: 'Rat King', provider: 'B2BSlots' },
  { id: 1251, name: 'Generous Jack', provider: 'B2BSlots' },
  { id: 1252, name: 'Dinopolis', provider: 'B2BSlots' },
  { id: 1253, name: 'Jaguar Drop', provider: 'B2BSlots' },
  { id: 1254, name: 'Dj Cat', provider: 'B2BSlots' },
  { id: 1255, name: 'BigBite', provider: 'B2BSlots' },
  { id: 1256, name: 'Big Bam Book', provider: 'B2BSlots' },
  { id: 1257, name: 'Retro Sweets', provider: 'B2BSlots' },
  { id: 1258, name: '10 Flaming Bisons', provider: 'B2BSlots' },
  { id: 1259, name: 'Mystery Nile', provider: 'B2BSlots' },
  { id: 1260, name: 'Razor Ways', provider: 'B2BSlots' },
  { id: 1261, name: 'The Grand Show', provider: 'B2BSlots' },
  { id: 1262, name: 'Mad Blast', provider: 'B2BSlots' },
  { id: 1263, name: 'Razor Returns', provider: 'B2BSlots' },
  { id: 1264, name: 'Big Bamboo', provider: 'B2BSlots' },
];

export const THREE_OAKS_GAME_NAMES_WITH_IDS = [
  { id: 1265, name: 'Dancing Joker', provider: 'B2BSlots' },
  { id: 1266, name: 'Coin Express', provider: 'B2BSlots' },
  { id: 1267, name: 'Big Heist', provider: 'B2BSlots' },
  { id: 1268, name: 'Eggs of Gold', provider: 'B2BSlots' },
  { id: 1269, name: 'Grab More Gold', provider: 'B2BSlots' },
  { id: 1270, name: 'Dragon Pearls', provider: 'B2BSlots' },
  { id: 1271, name: 'Sun of Egypt', provider: 'B2BSlots' },
  { id: 1272, name: 'Super Rich God', provider: 'B2BSlots' },
  { id: 1273, name: 'Thunder of Olympus', provider: 'B2BSlots' },
  { id: 1274, name: 'Sun of Egypt 2', provider: 'B2BSlots' },
  { id: 1275, name: 'Sun of Egypt 3', provider: 'B2BSlots' },
  { id: 1276, name: 'Sun of Egypt 4', provider: 'B2BSlots' },
  { id: 1277, name: 'Book of Sun Multichance', provider: 'B2BSlots' },
  { id: 1278, name: 'Magic Apple', provider: 'B2BSlots' },
  { id: 1279, name: 'Magic Apple 2', provider: 'B2BSlots' },
  { id: 1280, name: 'Olympian Gods', provider: 'B2BSlots' },
  { id: 1281, name: 'Scarab Boost', provider: 'B2BSlots' },
  { id: 1282, name: 'Scarab Riches', provider: 'B2BSlots' },
  { id: 1283, name: 'Scarab Temple', provider: 'B2BSlots' },
  { id: 1284, name: 'Super Marble', provider: 'B2BSlots' },
  { id: 1285, name: 'Wolf Night', provider: 'B2BSlots' },
  { id: 1286, name: '15 Dragon Pearls', provider: 'B2BSlots' },
  { id: 1287, name: 'Aztec Sun', provider: 'B2BSlots' },
  { id: 1288, name: 'Dragon Wealth', provider: 'B2BSlots' },
  { id: 1289, name: '3 Coins Egypt', provider: 'B2BSlots' },
  { id: 1290, name: '3 Coins', provider: 'B2BSlots' },
  { id: 1291, name: '777 Fruity Classic', provider: 'B2BSlots' },
  { id: 1292, name: '777 Gems Respin', provider: 'B2BSlots' },
  { id: 1293, name: 'Hot Fire Fruits', provider: 'B2BSlots' },
  { id: 1294, name: 'Moon Sisters', provider: 'B2BSlots' },
  { id: 1295, name: 'Fortune Globe', provider: 'B2BSlots' },
  { id: 1296, name: 'Crystal Scarabs', provider: 'B2BSlots' },
  { id: 1297, name: 'Gold Express', provider: 'B2BSlots' },
  { id: 1298, name: 'Golden Teapot', provider: 'B2BSlots' },
];
