import { ApiProperty } from '@nestjs/swagger';
import { IsNumber, IsString, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';

class InitRealSessionParamsDto {
    @ApiProperty({ description: 'Partner alias (from your provider settings)', example: 'RBT' })
    @IsString()
    partnerAlias: string;

    @ApiProperty({ description: 'Partner session ID (generated by you)', example: 'user_1_session_123' })
    @IsString()
    partnerSession: string;

    @ApiProperty({ description: 'Game ID from Superomatic', example: 288 })
    @IsNumber()
    gameId: number;

    @ApiProperty({ description: 'Currency code', example: 'RUB' })
    @IsString()
    currency: string;

    @ApiProperty({ description: 'Freerounds ID (optional)', example: 98765, required: false })
    @IsNumber()
    freeroundsId?: number;
}

export class InitRealSessionDto {
    @ApiProperty({ description: 'User ID', example: 1 })
    @IsNumber()
    userId: number;

    @ApiProperty({ description: 'Site ID', example: 1 })
    @IsNumber()
    siteId: number;

    @ApiProperty({
        description: 'Real session parameters',
        type: InitRealSessionParamsDto
    })
    @ValidateNested()
    @Type(() => InitRealSessionParamsDto)
    params: InitRealSessionParamsDto;
}
